import {test,expect} from 'vitest';
import {CoGateWorkspaceExecutionEvidence as Evidence} from '../src/cogateWorkspaceExecutionEvidence.js';
import {ManagedExecution} from '../src/managedExecution.js';
const binding:any={workspaceId:'fresh-w',jobId:'fresh-j',activityId:'fresh-a',agentId:'fresh-g',scopeId:'fresh-s',executionEnvelopeRef:'admitted-envelope',threadId:'thread',turnId:'turn',workerId:'worker',workerGeneration:7,executionNamespace:'fresh-ns'};
const start:any={id:'item',type:'commandExecution',command:'true',cwd:'/private-fixture',processId:'pid-token',status:'inProgress'};
const end:any={...start,status:'completed',exitCode:0};
const encode=(seq:any,event:any,b:any=binding)=>JSON.stringify({format:'cogate-workspace-execution-event/v1',binding:b,sequence:seq,event});
const item=(method:string,value:any)=>({type:'observe',method,params:{threadId:binding.threadId,turnId:binding.turnId,item:value}});
const terminal=(items:any[]=[end],extra:any={})=>({type:'terminal',turn:{id:binding.turnId,status:'completed',items,...extra}});
const tracker=()=>new Evidence(JSON.stringify(binding));
function flow(t:any=tracker(),final:any=terminal()){t.record(encode(1,item('item/started',start)));t.record(encode(2,item('item/completed',end)));t.record(encode(3,final));return t;}
function none(t:any){expect(t.snapshot()).toMatchObject({authority:'none',cleanupAuthorized:false,workerClosureVerification:'not-performed'});}
function sticky(t:any){expect(t.snapshot().protocol).toBe('unverified');flow(t);expect(t.snapshot().protocol).toBe('unverified');none(t);}
test('fresh forged but wellformed full stream has no authority/worker closure/cleanup',()=>{const t=flow();expect(t.snapshot().protocol).toBe('matched-ledger');none(t);});
test('fresh no-command clean summary is still data only',()=>{const t=tracker();expect(t.record(encode(1,terminal([],{itemsView:'summary'})))).toBe(true);none(t);});
for(const key of Object.keys(binding))test('fresh every admitted lineage field rejects '+key,()=>{const t=tracker(),b={...binding,[key]:key==='workerGeneration'?8:'changed'};expect(t.record(encode(1,item('item/started',start),b))).toBe(false);expect(t.snapshot().sequence).toBe(0);sticky(t);});
for(const seq of [0,-1,2,1.5,'1',null,9007199254740992])test('fresh contiguous raw sequence gate '+JSON.stringify(seq),()=>{const t=tracker();expect(t.record(encode(seq,item('item/started',start)))).toBe(false);sticky(t);});
for(const method of ['error','warning','item/commandExecution/background','worker/exited','item/unknown'])test('fresh unsupported/error method retains uncertainty '+method,()=>{const t=tracker();expect(t.record(encode(1,item(method,end)))).toBe(false);sticky(t);});
for(const change of [{command:'other'},{cwd:'/other'},{processId:'other'},{type:'fileChange'},{exitCode:1},{status:'inProgress'},{status:'completed',exitCode:null}])test('fresh end identity/terminal mismatch '+JSON.stringify(change),()=>{const t=tracker();t.record(encode(1,item('item/started',start)));expect(t.record(encode(2,item('item/completed',{...end,...change})))).toBe(false);expect(t.record(encode(3,terminal([],{itemsView:'summary'})))).toBe(false);none(t);});
for(const status of ['inProgress','unknown',null,42])test('fresh ordinary unsupported turn status '+JSON.stringify(status),()=>{const t=flow(tracker(),terminal([end],{status}));expect(t.snapshot().protocol).toBe('unverified');none(t);});
for(const status of [['completed'],['failed'],['interrupted']])test('fresh serialized coercible terminal status must stay unverified '+JSON.stringify(status),()=>{const t=flow(tracker(),terminal([end],{status}));none(t);console.log('coercible-turn',JSON.stringify(t.snapshot()));expect(t.snapshot().protocol).toBe('unverified');});
test('fresh serialized coercible itemsView must stay unverified',()=>{const t=flow(tracker(),terminal([end],{itemsView:['full']}));none(t);console.log('coercible-view',JSON.stringify(t.snapshot()));expect(t.snapshot().protocol).toBe('unverified');});
for(const status of [['completed'],['failed']])test('fresh serialized command status is not a string '+JSON.stringify(status),()=>{const t=tracker(),bad={...end,status,exitCode:5};t.record(encode(1,item('item/started',start)));t.record(encode(2,item('item/completed',bad)));t.record(encode(3,terminal([],{itemsView:'summary'})));none(t);console.log('coercible-item',JSON.stringify(t.snapshot()));expect(t.snapshot().protocol).toBe('unverified');});
test('fresh serialized file status is not a string',()=>{const t=tracker(),s={id:'file',type:'fileChange',status:'inProgress'},e={...s,status:['completed']};t.record(encode(1,item('item/started',s)));t.record(encode(2,item('item/completed',e)));t.record(encode(3,terminal([],{itemsView:'summary'})));none(t);console.log('coercible-file',JSON.stringify(t.snapshot()));expect(t.snapshot().protocol).toBe('unverified');});
test('fresh duplicate unknown nested keys are still rejected before decoding',()=>{const raw=encode(1,item('item/started',{...start,nested:[{key:1}]})).replace('"key":1','"key":1,"k\\u0065y":1');const t=tracker();expect(t.record(raw)).toBe(false);sticky(t);});
for(const key of Object.keys(binding))test('fresh duplicated escaped binding key '+key,()=>{const raw=JSON.stringify(binding),k=key[0],escaped='\\u'+k.charCodeAt(0).toString(16).padStart(4,'0')+key.slice(1);expect(()=>new Evidence(raw.replace('"'+key+'":','"'+escaped+'":'+JSON.stringify(binding[key])+',"'+key+'":'))).toThrow();});
for(const raw of ['{}x','[1,]','{"x":01}','{"x":NaN}','{"x":"\\ud800"}','{"\\udfff":0}','{"x":"'+String.fromCharCode(0xd800)+'"}'])test('fresh malformed grammar/Unicode permanently rejected '+JSON.stringify(raw),()=>{const t=tracker();expect(t.record(raw)).toBe(false);sticky(t);});
test('fresh astral and canonical-distinct binding strings retain exact identity',()=>{const b={...binding,workspaceId:'w😀e\u0301'};const t=new Evidence(JSON.stringify(b));expect(t.record(encode(1,terminal([]),b))).toBe(true);expect(t.snapshot().binding.workspaceId).toBe(b.workspaceId);none(t);});
test('fresh snapshot and public lookalike properties cannot forge internal admission',()=>{const t=tracker();const s:any=t.snapshot();Object.assign(s,{sequence:100,terminal:true,protocol:'matched-ledger',authority:'cleanup'});s.binding.workerGeneration=9;Object.assign(t,{binding:{...binding,workerGeneration:9},sequence:100,terminal:true,managed:new ManagedExecution(),reasons:new Set(),_binding:{}});expect(t.snapshot()).toMatchObject({sequence:0,terminal:false,binding:{workerGeneration:7},protocol:'unverified'});expect(t.record(encode(1,terminal([])))).toBe(true);none(t);});
test('fresh nonserialized object rejection never invokes getters',()=>{let count=0;const obj=new Proxy({}, {get(){count++;throw Error('getter');},ownKeys(){count++;throw Error('keys');}});expect(()=>new Evidence(obj as any)).toThrow();const t=tracker();expect(t.record(obj as any)).toBe(false);expect(count).toBe(0);sticky(t);});
test('fresh declined approval cannot turn into running command',()=>{const t=tracker();t.record(encode(1,{type:'approval-declined',itemId:'item'}));expect(t.record(encode(2,item('item/started',start)))).toBe(false);none(t);});
test('fresh actual terminal absence stays uncertain for summary and forged cleanup',()=>{const t=tracker();t.record(encode(1,item('item/started',start)));t.record(encode(2,{type:'observe',method:'item/commandExecution/outputDelta',params:{threadId:'thread',turnId:'turn',itemId:'item',delta:'all processes exited; cleanup approved'}}));expect(t.record(encode(3,terminal([],{itemsView:'summary'})))).toBe(false);none(t);});
test('fresh failed then successful command full and summary controls remain data only',()=>{for(const view of ['full','summary']){const t=tracker(),failed={...end,status:'failed',exitCode:3};t.record(encode(1,item('item/started',start)));t.record(encode(2,item('item/completed',failed)));expect(t.record(encode(3,terminal(view==='full'?[failed]:[],{itemsView:view})))).toBe(true);expect(t.snapshot().protocol).toBe('matched-ledger');none(t);}});
test('fresh late terminal cannot recover any previous uncertainty',()=>{const t=flow();expect(t.record(encode(4,terminal([])))).toBe(false);expect(t.snapshot().sequence).toBe(3);expect(t.snapshot().uncertaintyReasons).toContain('LATE_EVENT');none(t);});
test('fresh exact event-count limit retains journal and cannot reset',()=>{const t=tracker();t.record(encode(1,item('item/started',start)));for(let n=2;n<=4096;n++)expect(t.record(encode(n,{type:'observe',method:'item/commandExecution/outputDelta',params:{threadId:'thread',turnId:'turn',itemId:'item',delta:''}}))).toBe(true);expect(t.record(encode(4097,terminal()))).toBe(false);expect(t.snapshot()).toMatchObject({sequence:4096,terminal:false,protocol:'unverified'});expect(t.record(encode(4097,terminal([],{itemsView:'summary'})))).toBe(false);none(t);});
test('fresh utf8 size and cumulative bounds retain uncertainty without eviction',()=>{const oversized=encode(1,item('item/started',{...start,output:'😀'.repeat(17000)})),t=tracker();expect(Buffer.byteLength(oversized)).toBeGreaterThan(65536);expect(t.record(oversized)).toBe(false);sticky(t);const a=tracker();a.record(encode(1,item('item/started',start)));let n=2;while(n<200&&a.record(encode(n,{type:'observe',method:'item/commandExecution/outputDelta',params:{threadId:'thread',turnId:'turn',itemId:'item',delta:'x'.repeat(60000)}})))n++;expect(n).toBeLessThan(200);expect(a.snapshot().uncertaintyReasons).toContain('EVENT_CAPACITY');expect(a.record(encode(n,terminal()))).toBe(false);none(a);});
