import {test,expect,vi} from 'vitest';
import {PassThrough} from 'node:stream';
import {mkdtempSync} from 'node:fs';
import path from 'node:path';
import {loadConfig} from '../src/config.js';
import {createStdioBridgeRuntime} from '../src/stdioServer.js';
import {createHttpServer,installMcpOperationFence} from '../src/server.js';
import {BridgeStateStore} from '../src/stateStore.js';
import {RuntimeOperationFence} from '../src/runtimeOperationFence.js';
import {InProcessOperationalStateService} from '../src/stateService.js';
const upstream={listTools:async()=>({tools:[]}),callTool:async()=>({content:[]}),close:async()=>{}};
const catalog:any={getCatalog:async()=>({source:'codex-cli',fetchedAt:new Date().toISOString(),fingerprint:'a'.repeat(64),cached:true,stale:false,validation:'valid',models:[]})};
function fixture(){const root=mkdtempSync(path.join(process.env.TMPDIR!,'frontend-nf-'));return {config:loadConfig({CODEX_MCP_BRIDGE_NO_AUTH:'1',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:path.join(root,'state.sqlite'),CODEX_MCP_BRIDGE_MODEL_CATALOG_STATE_FILE:path.join(root,'models.json')}),state:new BridgeStateStore({file:':memory:'}),input:new PassThrough(),output:new PassThrough()};}
test('owned SDK callback quiescence rejects late delegation and retains original pending result',async()=>{let handler:any;const register=vi.fn((...args:any[])=>{handler=args.at(-1);});const server:any={server:{setRequestHandler:register}};const fence=new RuntimeOperationFence();installMcpOperationFence(server,fence);let finish!:(v:object)=>void;const receiver={original:true},result={value:'original'};server.server.setRequestHandler('fixture',{},function(this:any){expect(this).toBe(receiver);return new Promise<object>(r=>finish=r);});const pending=handler.call(receiver,{},{});fence.pinNonforcingShutdown();expect(fence.observeNonforcingExit().outcome).toBe('timeout');await expect(handler({},{})).rejects.toThrow('RUNTIME_NONFORCING_PINNED');finish(result);expect(await pending).toBe(result);expect(fence.observeNonforcingExit().exited).toBe(true);expect(()=>server.server.setRequestHandler('late',{},()=>{})).toThrow('RUNTIME_NONFORCING_PINNED');});
test('actual stdio nonforcing close disconnects ingress while preserving shared writer evidence',async()=>{const f=fixture();const before=(f.state as any).database.prepare('SELECT * FROM bridge_instances WHERE instance_id=?').get(f.state.bridgeInstanceId);const runtime=createStdioBridgeRuntime(f.config,upstream,{stateStore:f.state,modelCatalog:catalog,input:f.input,output:f.output});try{await runtime.start();await new Promise<void>(resolve=>setTimeout(resolve,20));expect((await runtime.closeNonforcing({allowSigkillEscalation:false,graceMs:50})).exited).toBe(true);expect(runtime.observeNonforcingExit().exited).toBe(true);await expect(runtime.start()).rejects.toThrow('RUNTIME_NONFORCING_PINNED');expect((f.state as any).database.prepare('SELECT * FROM bridge_instances WHERE instance_id=?').get(f.state.bridgeInstanceId)).toEqual(before);await runtime.close();}finally{f.state.close();f.input.destroy();f.output.destroy();}});
test('stdio ordinary-close history remains UNKNOWN under later explicit nonforcing close',async()=>{const f=fixture();const runtime=createStdioBridgeRuntime(f.config,upstream,{stateStore:f.state,modelCatalog:catalog,input:f.input,output:f.output});try{await runtime.start();await runtime.close();expect((await runtime.closeNonforcing({allowSigkillEscalation:false,graceMs:0})).outcome).toBe('uncertain');expect(runtime.observeNonforcingExit().outcome).toBe('uncertain');}finally{f.state.close();f.input.destroy();f.output.destroy();}});
test('invalid accessor policy never changes stdio admission or invokes the getter',async()=>{const f=fixture();const runtime=createStdioBridgeRuntime(f.config,upstream,{stateStore:f.state,modelCatalog:catalog,input:f.input,output:f.output});let reads=0;try{expect(()=>runtime.closeNonforcing({get allowSigkillEscalation(){reads++;return false;}})).toThrow('SHUTDOWN_POLICY_INVALID');expect(reads).toBe(0);await runtime.start();await runtime.close();}finally{f.state.close();f.input.destroy();f.output.destroy();}});
test('actual HTTP listener nonforcing close cannot be reopened and preserves shared writer evidence',async()=>{const f=fixture();const server=createHttpServer(f.config,upstream,catalog,{stateStore:f.state});try{await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const before=(f.state as any).database.prepare('SELECT * FROM bridge_instances WHERE instance_id=?').get(f.state.bridgeInstanceId);expect((await server.closeNonforcing({allowSigkillEscalation:false,graceMs:50})).exited).toBe(true);expect(server.listening).toBe(false);expect((await server.observeNonforcingExit()).exited).toBe(true);expect(()=>server.listen(0,'127.0.0.1')).toThrow('RUNTIME_NONFORCING_PINNED');expect((f.state as any).database.prepare('SELECT * FROM bridge_instances WHERE instance_id=?').get(f.state.bridgeInstanceId)).toEqual(before);}finally{if(server.listening)await new Promise<void>(resolve=>server.close(()=>resolve()));f.state.close();f.input.destroy();f.output.destroy();}});

test('stdio startup maintenance with a held original command remains UNKNOWN after settlement',async()=>{let settle!:(v:any)=>void;let started=false;const originalCommand=new Promise<any>(resolve=>settle=resolve);const execute=vi.spyOn(InProcessOperationalStateService.prototype,'execute').mockImplementation(()=>{started=true;return originalCommand;});const f=fixture();const runtime=createStdioBridgeRuntime(f.config,upstream,{stateStore:f.state,modelCatalog:catalog,input:f.input,output:f.output});try{await runtime.start();expect(started).toBe(true);const initial=await runtime.closeNonforcing({allowSigkillEscalation:false,graceMs:0});expect(initial.outcome).toBe('uncertain');settle({changed:0});await new Promise<void>(resolve=>setTimeout(resolve,5));expect(runtime.observeNonforcingExit().outcome).toBe('uncertain');expect(initial.outcome).toBe('uncertain');await expect(runtime.close()).rejects.toThrow('UNCONFIRMED');}finally{settle?.({changed:0});execute.mockRestore();f.state.close();f.input.destroy();f.output.destroy();}});
