import {expect,test,vi} from 'vitest';
import {McpEventsController} from '../src/mcpEvents.js';
import {loadConfig} from '../src/config.js';
import {EventDestinationVault} from '../src/mcpWebhook.js';
const token='a'.repeat(64),secret='whsec_'+Buffer.alloc(32,1).toString('base64');
function fixture(sender:any){const config=loadConfig({CODEX_MCP_BRIDGE_TOKEN:token,CODEX_MCP_BRIDGE_EVENTS_ENABLED:'1',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:process.env.HOME+'/not-opened.sqlite'});const id='owned-record',vault=new EventDestinationVault(token);const record:any={jobId:'job',id,revision:1,expiresAt:Date.now()+60000,delivery:'pending',nextAttemptAt:0,attempts:0,scopeId:'scope',event:{eventId:'original-event'},destination:vault.seal(id,{url:'https://example.com/events',secret})};const ledger={maintain:vi.fn(),list:vi.fn(()=>[record]),get:vi.fn(()=>record),save:vi.fn(()=>true)};const unsubscribe=vi.fn();const jobs:any={subscribeChanges:()=>unsubscribe,admissionStateStore:{mcpEvents:ledger}};const controller=new McpEventsController(config,jobs,{} as any,sender);record.principal=(controller as any).principal;(controller as any).requireJob=()=>{};return {controller,ledger,unsubscribe,record};}
test('queued event delivery is cancelled before it can touch the owned ledger',async()=>{vi.useFakeTimers();const sender=vi.fn();const f=fixture(sender);try{f.controller.pinNonforcingShutdown();await vi.advanceTimersByTimeAsync(10);expect(f.ledger.maintain).not.toHaveBeenCalled();expect(sender).not.toHaveBeenCalled();expect(f.unsubscribe).toHaveBeenCalledOnce();expect(f.controller.observeNonforcingExit().exited).toBe(true);}finally{vi.useRealTimers();}});
test('held event delivery settles without post-pin ledger writes and retains original response',async()=>{vi.useFakeTimers();let finish!:(v:any)=>void;const response={status:200,body:'original'};const sender=vi.fn(()=>new Promise(resolve=>finish=resolve));const f=fixture(sender);try{await vi.advanceTimersByTimeAsync(0);expect(sender).toHaveBeenCalledOnce();f.controller.pinNonforcingShutdown();expect(f.controller.observeNonforcingExit().outcome).toBe('timeout');const writes=f.ledger.save.mock.calls.length;finish(response);await vi.advanceTimersByTimeAsync(0);expect(f.ledger.save.mock.calls.length).toBe(writes);expect((f.controller as any).retainedResponses.get(f.record.id)).toBe(response);expect(f.controller.observeNonforcingExit().exited).toBe(true);}finally{finish?.(response);vi.useRealTimers();}});
test('event sender response accessor cannot execute or publish delivery acknowledgement',async()=>{vi.useFakeTimers();let reads=0;const response={get status(){reads++;return 200;}};const f=fixture(async()=>response);try{await vi.advanceTimersByTimeAsync(0);expect(reads).toBe(0);expect(f.ledger.save).toHaveBeenCalledOnce();expect((f.controller as any).retainedResponses.get(f.record.id)).toBe(response);expect((await f.controller.closeNonforcing()).outcome).toBe('uncertain');}finally{vi.useRealTimers();}});
test('event ordinary close history never becomes a positive nonforcing receipt',async()=>{vi.useFakeTimers();const f=fixture(vi.fn());try{await f.controller.close();expect((await f.controller.closeNonforcing()).outcome).toBe('uncertain');expect(f.controller.observeNonforcingExit().outcome).toBe('uncertain');}finally{vi.useRealTimers();}});
