import {test,expect,afterEach,vi} from 'vitest';import fs from 'node:fs';import fsp from 'node:fs/promises';import {syncBuiltinESMExports} from 'node:module';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {CodexRuntimeManager,observeRetainedCliLease} from '../src/codexRuntime.js';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();syncBuiltinESMExports();for(const r of roots.splice(0))await fsp.rm(r,{recursive:true});});
const selection:any={id:'fresh-created-fd',source:'terminal',command:'/private-fixture',physicalPath:'/private-fixture',version:'0.153.4'};
async function fixture(){const root=await fsp.mkdtemp(join(tmpdir(),'fd-owner-review-'));roots.push(root);return{root,manager:new CodexRuntimeManager({root,environment:{},discoverExternal:false})};}
async function hook(root:string,apply:(h:any,p:string)=>void){const nativeOpen=fsp.open;vi.spyOn(fsp,'open').mockImplementation(async(p:any,...args:any[])=>{const h=await Reflect.apply(nativeOpen,fsp,[p,...args]);if(String(p).startsWith(join(root,'.lease-')))apply(h,String(p));return h;});syncBuiltinESMExports();}
test('fresh original native writer and closer retain actual handle receiver and close once',async()=>{const f=await fixture();let writes=0,closes=0;await hook(f.root,(h)=>{const w=h.writeFile,c=h.close;h.writeFile=function(...a:any[]){expect(this).toBe(h);writes++;return Reflect.apply(w,this,a);};h.close=function(...a:any[]){expect(this).toBe(h);closes++;return Reflect.apply(c,this,a);};});const release=await f.manager.lease(selection);expect(writes).toBe(1);expect(closes).toBe(1);expect(observeRetainedCliLease(release)).toBe(true);await release();expect(closes).toBe(1);});
test('fresh gated native handle write keeps incomplete record unpublished until original write resolves',async()=>{const f=await fixture();let entered!:(v?:any)=>void,resume!:(v?:any)=>void;const inWrite=new Promise(r=>entered=r),gate=new Promise(r=>resume=r);await hook(f.root,h=>{const w=h.writeFile.bind(h);h.writeFile=async(...a:any[])=>{entered();await gate;return Reflect.apply(w,h,a);};});const pending=f.manager.lease(selection);await inWrite;expect(await fsp.readdir(join(f.root,'leases'))).toEqual([]);expect((await fsp.readdir(f.root)).filter(n=>n.startsWith('.lease-')).length).toBe(1);resume();const release=await pending;expect(observeRetainedCliLease(release)).toBe(true);expect((await fsp.readdir(f.root)).filter(n=>n.startsWith('.lease-'))).toEqual([]);});
test('fresh native handle write rejection preserves exact original error closes once and retains failed private temporary evidence',async()=>{const f=await fixture(),raw={error:'original write failed'};let closes=0;await hook(f.root,h=>{const c=h.close.bind(h);h.writeFile=async()=>{throw raw;};h.close=async()=>{closes++;return c();};});expect(await f.manager.lease(selection).catch(e=>e)).toBe(raw);expect(closes).toBe(1);expect(await fsp.readdir(join(f.root,'leases'))).toEqual([]);expect((await fsp.readdir(f.root)).filter(n=>n.startsWith('.lease-'))).toHaveLength(1);});
test('fresh native rename rejection preserves exact error after original descriptor closes',async()=>{const f=await fixture(),raw={error:'original rename failed'};let closes=0;await hook(f.root,h=>{const c=h.close.bind(h);h.close=async()=>{closes++;return c();};});const nativeRename=fsp.rename;vi.spyOn(fsp,'rename').mockImplementation((a:any,b:any)=>String(a).startsWith(join(f.root,'.lease-'))?Promise.reject(raw):nativeRename(a,b));syncBuiltinESMExports();expect(await f.manager.lease(selection).catch(e=>e)).toBe(raw);expect(closes).toBe(1);expect(await fsp.readdir(join(f.root,'leases'))).toEqual([]);expect((await fsp.readdir(f.root)).filter(n=>n.startsWith('.lease-'))).toHaveLength(1);});
test('fresh actual close completed then rejected preserves raw rejection without granting capability',async()=>{const f=await fixture(),raw={error:'completed native close failure'};let closes=0;await hook(f.root,h=>{const c=h.close.bind(h);h.close=async()=>{closes++;await c();throw raw;};});const result=await f.manager.lease(selection).catch(e=>e);expect(result).toBe(raw);expect(observeRetainedCliLease(result)).toBe(false);expect(closes).toBe(1);expect((await fsp.readdir(join(f.root,'leases'))).length).toBe(1);expect((await fsp.readdir(f.root)).filter(n=>n.startsWith('.lease-'))).toEqual([]);});
test('fresh creation fstat failure preserves original error and still closes own descriptor',async()=>{const f=await fixture(),raw={error:'creation fstat failed'},nativeStat=fs.fstatSync;let fd=-1,closes=0;await hook(f.root,h=>{fd=h.fd;const c=h.close.bind(h);h.close=async()=>{closes++;return c();};});vi.spyOn(fs,'fstatSync').mockImplementation((p:any,...args:any[])=>{if(p===fd)throw raw;return Reflect.apply(nativeStat,fs,[p,...args]);});syncBuiltinESMExports();expect(await f.manager.lease(selection).catch(e=>e)).toBe(raw);expect(closes).toBe(1);expect(await fsp.readdir(join(f.root,'leases'))).toEqual([]);});
test('fresh existing temporary collision is not deleted when exclusive creation never succeeded',async()=>{const f=await fixture(),nativeOpen=fsp.open;let collision='';const marker=Buffer.from('original unrelated private file');vi.spyOn(fsp,'open').mockImplementation(async(p:any,...args:any[])=>{if(String(p).startsWith(join(f.root,'.lease-'))){collision=String(p);await fsp.writeFile(p,marker,{mode:0o600,flag:'wx'});}return Reflect.apply(nativeOpen,fsp,[p,...args]);});syncBuiltinESMExports();const original=await f.manager.lease(selection).catch(e=>e);expect(original.code).toBe('EEXIST');expect(await fsp.readFile(collision)).toEqual(marker);});
test('fresh completed publish does not delete a new unowned temporary entry created during close',async()=>{const f=await fixture();let collision='';const marker=Buffer.from('new private file after original renamed');await hook(f.root,(h,p)=>{const c=h.close.bind(h);h.close=async()=>{await c();collision=p;await fsp.writeFile(p,marker,{mode:0o600,flag:'wx'});};});const release=await f.manager.lease(selection);expect(observeRetainedCliLease(release)).toBe(true);expect(await fsp.readFile(collision)).toEqual(marker);});

test('simultaneous publication and native close failures preserve both original objects',async()=>{
 const f=await fixture(),writeError={original:'write'},closeError={original:'close'};let closes=0;
 await hook(f.root,h=>{const close=h.close.bind(h);h.writeFile=async()=>{throw writeError;};h.close=async()=>{closes++;await close();throw closeError;};});
 const error=await f.manager.lease(selection).catch(e=>e);expect(error).toBeInstanceOf(AggregateError);
 expect(error.errors[0]).toBe(writeError);expect(error.errors[1]).toBe(closeError);expect(error.cause).toBe(writeError);
 expect(closes).toBe(1);expect(await fsp.readdir(join(f.root,'leases'))).toEqual([]);
 expect((await fsp.readdir(f.root)).filter(n=>n.startsWith('.lease-'))).toHaveLength(1);
});

test('ordinary publication without POSIX UID remains supported with unconfirmed passive proof',async()=>{
 const f=await fixture(),original=Object.getOwnPropertyDescriptor(process,'getuid')!;
 let release:(()=>Promise<void>)|undefined;
 try{Object.defineProperty(process,'getuid',{...original,value:undefined});release=await f.manager.lease(selection);
  expect(observeRetainedCliLease(release)).toBe(false);expect(await fsp.readdir(join(f.root,'leases'))).toHaveLength(1);
 }finally{Object.defineProperty(process,'getuid',original);if(release)await release();}
 expect(await fsp.readdir(join(f.root,'leases'))).toEqual([]);
});
