import {test,expect,afterEach,vi} from 'vitest';import fs from 'node:fs';import fsp from 'node:fs/promises';import {syncBuiltinESMExports} from 'node:module';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {CodexRuntimeManager,observeRetainedCliLease} from '../src/codexRuntime.js';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();syncBuiltinESMExports();for(const r of roots.splice(0))await fsp.rm(r,{recursive:true});});
async function interceptOriginalWrites(root:string,callback:(p:any,data:any,opt:any)=>Promise<void>){
 const nativeOpen=fsp.open;
 vi.spyOn(fsp,'open').mockImplementation(async(p:any,flags:any,mode:any)=>{
  const handle=await nativeOpen(p,flags,mode);
  if(String(p).startsWith(join(root,'.lease-'))){
   const nativeWrite=handle.writeFile.bind(handle);
   handle.writeFile=async(data:any,opt:any)=>{await nativeWrite(data,opt);await callback(p,data,opt);};
  }
  return handle;
 });syncBuiltinESMExports();
}
const selection:any={id:'fresh-publication',source:'terminal',command:'/private-fixture',physicalPath:'/private-fixture',version:'0.153.4'};
async function rootFixture(){const root=await fsp.mkdtemp(join(tmpdir(),'fresh-successor-boundary-'));roots.push(root);return{root,manager:new CodexRuntimeManager({root,environment:{},discoverExternal:false})};}
async function ready(){const f=await rootFixture(),release=await f.manager.lease(selection),file=join(f.root,'leases',(await fsp.readdir(join(f.root,'leases')))[0]);return{...f,release,file};}
test('fresh publisher-created temporary inode cannot be replaced before pre-rename snapshot',async()=>{const f=await rootFixture(),nativeWrite=fsp.writeFile;let original:bigint|undefined,replacement:bigint|undefined;await interceptOriginalWrites(f.root,async(p:any,data:any,opt:any)=>{if(String(p).startsWith(join(f.root,'.lease-'))){original=(await fsp.lstat(p,{bigint:true})).ino;const bytes=await fsp.readFile(p);await fsp.rename(p,p+'.original');await nativeWrite(p,bytes,{mode:0o600,flag:'wx'});replacement=(await fsp.lstat(p,{bigint:true})).ino;await fsp.rm(p+'.original');}});syncBuiltinESMExports();const release=await f.manager.lease(selection);expect(original).toBeDefined();expect(replacement).not.toBe(original);const observed=observeRetainedCliLease(release);console.log('pre-snapshot-inode-replacement',{original:String(original),replacement:String(replacement),observed});expect(observed).toBe(false);});
test('fresh changed temporary payload before snapshot cannot acquire original capability',async()=>{const f=await rootFixture(),nativeWrite=fsp.writeFile;await interceptOriginalWrites(f.root,async(p:any,data:any,opt:any)=>{if(String(p).startsWith(join(f.root,'.lease-')))await nativeWrite(p,JSON.stringify({...JSON.parse(String(data)),startedAt:'not-original'}));});syncBuiltinESMExports();const release=await f.manager.lease(selection);expect(observeRetainedCliLease(release)).toBe(false);});
test('fresh original directory replaced during temporary write cannot acquire authority',async()=>{const f=await rootFixture(),nativeWrite=fsp.writeFile;await interceptOriginalWrites(f.root,async(p:any,data:any,opt:any)=>{if(String(p).startsWith(join(f.root,'.lease-'))){await fsp.rename(join(f.root,'leases'),join(f.root,'leases.original'));await fsp.mkdir(join(f.root,'leases'),{mode:0o700});}});syncBuiltinESMExports();expect(observeRetainedCliLease(await f.manager.lease(selection))).toBe(false);});
test('fresh post-rename byte-identical new inode cannot acquire authority',async()=>{const f=await rootFixture(),nativeRename=fsp.rename;vi.spyOn(fsp,'rename').mockImplementation(async(a:any,b:any)=>{await nativeRename(a,b);if(String(b).startsWith(join(f.root,'leases')+'/')){const bytes=await fsp.readFile(b);await nativeRename(b,b+'.original');await fsp.writeFile(b,bytes,{mode:0o600,flag:'wx'});await fsp.rm(b+'.original');}});syncBuiltinESMExports();expect(observeRetainedCliLease(await f.manager.lease(selection))).toBe(false);});
test('fresh post-rename foreign PID remains unsupported even with valid private file',async()=>{const f=await rootFixture(),nativeRename=fsp.rename;vi.spyOn(fsp,'rename').mockImplementation(async(a:any,b:any)=>{await nativeRename(a,b);if(String(b).startsWith(join(f.root,'leases')+'/'))await fsp.writeFile(b,JSON.stringify({...JSON.parse((await fsp.readFile(b)).toString()),pid:process.pid+1}));});syncBuiltinESMExports();expect(observeRetainedCliLease(await f.manager.lease(selection))).toBe(false);});
test('fresh release callback reentry sees invalidated capability before original synchronous throw',async()=>{const f=await ready(),nativeRm=fsp.rm,raw={original:'synchronous rm failure'};let during:boolean|undefined;vi.spyOn(fsp,'rm').mockImplementation((p:any,o:any)=>{if(String(p)===f.file){during=observeRetainedCliLease(f.release);throw raw;}return nativeRm(p,o);});syncBuiltinESMExports();let caught:any;try{f.release();}catch(e){caught=e;}expect(caught).toBe(raw);expect(during).toBe(false);expect(observeRetainedCliLease(f.release)).toBe(false);expect((await fsp.readFile(f.file)).length).toBeGreaterThan(0);});
test('fresh release original pending rejected Promise identity and failure history are preserved',async()=>{const f=await ready(),nativeRm=fsp.rm,raw={original:'async rm failure'};let reject!:(e:any)=>void;const pending=new Promise<void>((_,r)=>reject=r);vi.spyOn(fsp,'rm').mockImplementation((p:any,o:any)=>String(p)===f.file?pending:nativeRm(p,o));syncBuiltinESMExports();const result=f.release();expect(result).toBe(pending);expect(observeRetainedCliLease(f.release)).toBe(false);reject(raw);expect(await result.catch(e=>e)).toBe(raw);expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh reentrant original release while stable read is running cannot return positive authority',async()=>{const f=await ready(),nativeRead=fs.readSync;let invoked=false,pending:Promise<void>|undefined;vi.spyOn(fs,'readSync').mockImplementation((...args:any[])=>{if(!invoked){invoked=true;pending=f.release();}return Reflect.apply(nativeRead,fs,args as any);});syncBuiltinESMExports();const observed=observeRetainedCliLease(f.release);try{console.log('read-reentry-release',{invoked,observed});expect(invoked).toBe(true);expect(observed).toBe(false);}finally{await pending;}expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh close descriptor failure invalidates retained authority with unchanged bytes',async()=>{const f=await ready(),nativeClose=fs.closeSync;vi.spyOn(fs,'closeSync').mockImplementation(fd=>{nativeClose(fd);throw Error('controlled completed close failure');});syncBuiltinESMExports();expect(observeRetainedCliLease(f.release)).toBe(false);vi.restoreAllMocks();syncBuiltinESMExports();expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh stable read failure invalidates retained authority without release',async()=>{const f=await ready(),bytes=await fsp.readFile(f.file);vi.spyOn(fs,'readSync').mockImplementation(()=>{throw Error('controlled read failure');});syncBuiltinESMExports();expect(observeRetainedCliLease(f.release)).toBe(false);vi.restoreAllMocks();syncBuiltinESMExports();expect(observeRetainedCliLease(f.release)).toBe(false);expect((await fsp.readFile(f.file)).equals(bytes)).toBe(true);});
