import {test,expect,afterEach,vi} from 'vitest';import fsPromises from 'node:fs/promises';import {mkdtemp,readdir,readFile,writeFile,chmod,chown,lstat,link,rename,mkdir,rm,symlink,realpath} from 'node:fs/promises';import {syncBuiltinESMExports} from 'node:module';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {CodexRuntimeManager,observeRetainedCliLease} from '../src/codexRuntime.js';
const roots:string[]=[];afterEach(async()=>{vi.restoreAllMocks();syncBuiltinESMExports();for(const root of roots.splice(0))await rm(root,{recursive:true});});
const selection:any={id:'review',source:'terminal',command:'/private-fixture-codex',physicalPath:'/private-fixture-codex',version:'0.153.4'};
async function fixture(){const root=await mkdtemp(join(tmpdir(),'independent-retained-')),manager=new CodexRuntimeManager({root,discoverExternal:false,environment:{}});roots.push(root);const release=await manager.lease(selection),directory=join(root,'leases'),file=join(directory,(await readdir(directory))[0]);return {root,manager,release,directory,file};}
test('fresh unchanged original capability is a passive byte-identical normal control',async()=>{const f=await fixture(),bytes=await readFile(f.file),before=await lstat(f.file,{bigint:true});expect(observeRetainedCliLease(f.release)).toBe(true);expect(observeRetainedCliLease(f.release)).toBe(true);expect((await readFile(f.file)).equals(bytes)).toBe(true);const after=await lstat(f.file,{bigint:true});expect(after.ino).toBe(before.ino);expect(after.mtimeNs).toBe(before.mtimeNs);expect(after.ctimeNs).toBe(before.ctimeNs);expect((after.mode&0o7777n)).toBe(0o600n);});
test('fresh unknown bound and proxy capabilities do not execute any callback/trap',async()=>{const f=await fixture();let traps=0;const proxy=new Proxy(f.release,{apply(){traps++;throw Error('no-call');},get(){traps++;throw Error('no-get');}});expect(observeRetainedCliLease(f.release.bind(undefined))).toBe(false);expect(observeRetainedCliLease(proxy)).toBe(false);expect(traps).toBe(0);expect(observeRetainedCliLease(f.release)).toBe(true);});
test('fresh same-inode same bytes rewrite invalidates original nanosecond history',async()=>{const f=await fixture(),before=await lstat(f.file,{bigint:true}),bytes=await readFile(f.file);await writeFile(f.file,bytes);const after=await lstat(f.file,{bigint:true});expect(after.ino).toBe(before.ino);expect((await readFile(f.file)).equals(bytes)).toBe(true);expect(observeRetainedCliLease(f.release)).toBe(false);expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh byte alteration restored before first observe still cannot restore original identity',async()=>{const f=await fixture(),bytes=await readFile(f.file);await writeFile(f.file,Buffer.alloc(bytes.length,32));await writeFile(f.file,bytes);expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh missing path cannot erase historical failed evidence when original inode restored',async()=>{const f=await fixture();await rename(f.file,f.file+'.held');expect(observeRetainedCliLease(f.release)).toBe(false);await rename(f.file+'.held',f.file);expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh directory replacement with same file bytes is not the original publication',async()=>{const f=await fixture(),bytes=await readFile(f.file);await rename(f.directory,f.directory+'.held');await mkdir(f.directory,{mode:0o700});await writeFile(f.file,bytes,{mode:0o600});expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh file changed to owner-read-only remains unconfirmed',async()=>{const f=await fixture();await chmod(f.file,0o400);expect(observeRetainedCliLease(f.release)).toBe(false);await chmod(f.file,0o600);expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh extra hardlink revokes evidence even after removal',async()=>{const f=await fixture();await link(f.file,f.file+'.link');expect(observeRetainedCliLease(f.release)).toBe(false);await rm(f.file+'.link');expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh oversized current payload is bounded and permanently false',async()=>{const f=await fixture();await writeFile(f.file,JSON.stringify({pid:process.pid,data:'x'.repeat(32769)}));expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh configured root alias is canonicalized before original publication',async()=>{const root=await mkdtemp(join(tmpdir(),'independent-retained-alias-'));roots.push(root);await mkdir(join(root,'real'),{mode:0o700});await symlink(join(root,'real'),join(root,'alias'));const manager=new CodexRuntimeManager({root:join(root,'alias'),discoverExternal:false,environment:{}}),release=await manager.lease(selection);expect(manager.root).toBe(await realpath(join(root,'alias')));expect(observeRetainedCliLease(release)).toBe(true);expect((await readdir(join(root,'real/leases'))).length).toBe(1);});
test('fresh ordinary original release starting immediately invalidates capability before unlink completes',async()=>{const f=await fixture();expect(observeRetainedCliLease(f.release)).toBe(true);const pending=f.release();const during=observeRetainedCliLease(f.release);console.log('ordinary-release-start',{during});try{expect(during).toBe(false);}finally{await pending;}expect(observeRetainedCliLease(f.release)).toBe(false);});
test('fresh publication bytes changed after rename cannot be rebound as original capability',async()=>{const root=await mkdtemp(join(tmpdir(),'independent-retained-publish-'));roots.push(root);const originalRename=fsPromises.rename;let published:Buffer|undefined,tampered:Buffer|undefined;vi.spyOn(fsPromises,'rename').mockImplementation(async(source:any,dest:any)=>{await originalRename(source,dest);if(String(dest).startsWith(join(root,'leases')+'/')){published=await readFile(dest);tampered=Buffer.from(JSON.stringify({...JSON.parse(published.toString()),startedAt:'changed-after-publication'}));await writeFile(dest,tampered);}});syncBuiltinESMExports();const manager=new CodexRuntimeManager({root,discoverExternal:false,environment:{}}),release=await manager.lease(selection);expect(published).toBeDefined();expect(tampered).toBeDefined();const observed=observeRetainedCliLease(release);console.log('publication-rebind',{publishedSHA:createHash('sha256').update(published!).digest('hex'),currentSHA:createHash('sha256').update(tampered!).digest('hex'),observed});expect(observed).toBe(false);});
test('fresh changed supplementary GID is not accepted as original owner metadata',async context=>{const f=await fixture(),s=await lstat(f.file),gid=process.getgroups?.().find(g=>g!==s.gid);if(gid===undefined){context.skip();return;}try{await chown(f.file,s.uid,gid);}catch(error){if((error as any).code==='EPERM'){context.skip();return;}throw error;}expect((await lstat(f.file)).gid).toBe(gid);expect(observeRetainedCliLease(f.release)).toBe(false);});

test('fresh published lease directory substituted with a symlink stays false',async()=>{const f=await fixture();await rename(f.directory,f.directory+'.held');await symlink(f.directory+'.held',f.directory);expect(observeRetainedCliLease(f.release)).toBe(false);});

 test('same bytes on a replacement inode during publication cannot acquire original capability',async()=>{
  const root=await mkdtemp(join(tmpdir(),'retained-replaced-publication-'));roots.push(root);
  const originalRename=fsPromises.rename;let originalInode:bigint|undefined,replacementInode:bigint|undefined;
  vi.spyOn(fsPromises,'rename').mockImplementation(async(source:any,dest:any)=>{
   await originalRename(source,dest);
   if(String(dest).startsWith(join(root,'leases')+'/')){
    const bytes=await readFile(dest);originalInode=(await lstat(dest,{bigint:true})).ino;
    await originalRename(dest,dest+'.held');await writeFile(dest,bytes,{mode:0o600,flag:'wx'});
    replacementInode=(await lstat(dest,{bigint:true})).ino;
   }
  });syncBuiltinESMExports();
  const manager=new CodexRuntimeManager({root,discoverExternal:false,environment:{}}),release=await manager.lease(selection);
  expect(originalInode).toBeDefined();expect(replacementInode).not.toBe(originalInode);expect(observeRetainedCliLease(release)).toBe(false);
 });
