// Retained exact 019b539 independent assertions; imports adapted; owned-DB final assertion requires actual close under the new continuation contract. Original reviewer source remains frozen.
import {test,expect,vi,afterEach} from 'vitest';
import {loadConfig} from '../src/config.js';
import {createHttpServer} from '../src/server.js';
import {createStdioBridgeRuntime} from '../src/stdioServer.js';
import {RuntimeOperationFence} from '../src/runtimeOperationFence.js';
import {BridgeStateStore} from '../src/stateStore.js';
import {PassThrough} from 'node:stream';
import {mkdtempSync} from 'node:fs';
import {createConnection} from 'node:net';
import {McpServer} from '@modelcontextprotocol/server';
import Database from 'better-sqlite3';
import path from 'node:path';
const upstream:any={listTools:async()=>({tools:[]}),callTool:async()=>({content:[]}),close:async()=>{}};
const catalog:any={getCatalog:async()=>({source:'codex-cli',fetchedAt:new Date().toISOString(),fingerprint:'a'.repeat(64),cached:true,stale:false,validation:'valid',models:[]})};
const pause=(ms=20)=>new Promise<void>(r=>setTimeout(r,ms));
function fixture(){const root=mkdtempSync(path.join(process.env.TMPDIR!,'review-host-'));return {config:loadConfig({CODEX_MCP_BRIDGE_NO_AUTH:'1',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:path.join(root,'owned.sqlite'),CODEX_MCP_BRIDGE_MODEL_CATALOG_STATE_FILE:path.join(root,'models.json')}),input:new PassThrough(),output:new PassThrough()};}
afterEach(()=>vi.restoreAllMocks());
test('real HTTP upgraded socket blocks receipt until fixture gracefully ends',async()=>{const f=fixture(),state=new BridgeStateStore({file:':memory:'}),server=createHttpServer(f.config,upstream,catalog,{stateStore:state});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));await pause();let upgraded!:()=>void;const ready=new Promise<void>(r=>upgraded=r);server.on('upgrade',(_request,peer)=>{peer.on('end',()=>peer.end());upgraded();});const port=(server.address() as any).port,socket=createConnection({host:'127.0.0.1',port});socket.on('error',()=>{});await new Promise<void>(r=>socket.once('connect',r));socket.write('GET /upgrade HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: Upgrade\r\nUpgrade: fixture\r\n\r\n');await ready;const before=(state as any).database.prepare('SELECT * FROM bridge_instances').all();try{const initial=await server.closeNonforcing({allowSigkillEscalation:false,graceMs:0});expect(initial.exited).toBe(false);expect(server.observeNonforcingExit().exited).toBe(false);const done=new Promise<void>(r=>socket.once('close',r));socket.end();await done;await pause();expect(server.observeNonforcingExit().exited).toBe(true);expect(initial.exited).toBe(false);expect((state as any).database.prepare('SELECT * FROM bridge_instances').all()).toEqual(before);expect(()=>server.listen(0,'127.0.0.1')).toThrow('PINNED');}finally{socket.end();state.close();f.input.destroy();f.output.destroy();}});
test('real stdio pipeline disconnects, removes input pipe, preserves shared owner rows',async()=>{const f=fixture(),state=new BridgeStateStore({file:':memory:'}),runtime=createStdioBridgeRuntime(f.config,upstream,{stateStore:state,modelCatalog:catalog,input:f.input,output:f.output});try{await runtime.start();await pause();const before=(state as any).database.prepare('SELECT * FROM bridge_instances').all();expect((await runtime.closeNonforcing({allowSigkillEscalation:false,graceMs:50})).exited).toBe(true);expect((f.input as any)._readableState.pipes.length).toBe(0);f.input.write('{}\n');expect(runtime.observeNonforcingExit().exited).toBe(true);await expect(runtime.start()).rejects.toThrow('PINNED');expect((state as any).database.prepare('SELECT * FROM bridge_instances').all()).toEqual(before);}finally{state.close();f.input.destroy();f.output.destroy();}});
test('owned stdio quiescent close confirms actual native DB close without retiring row',async()=>{const f=fixture(),owners:BridgeStateStore[]=[];const p=BridgeStateStore.prototype.pinNonforcingShutdown;vi.spyOn(BridgeStateStore.prototype,'pinNonforcingShutdown').mockImplementation(function(this:BridgeStateStore){owners.push(this);return p.call(this);});const runtime=createStdioBridgeRuntime(f.config,upstream,{modelCatalog:catalog,input:f.input,output:f.output});try{await runtime.start();await pause();const read=new Database(f.config.stateDatabaseFile,{readonly:true}),before=read.prepare('SELECT * FROM bridge_instances').all();expect((await runtime.closeNonforcing({allowSigkillEscalation:false,graceMs:50})).exited).toBe(true);expect((owners[0] as any).database.open).toBe(false);expect(owners[0].observeNonforcingExit().exited).toBe(true);expect(read.prepare('SELECT * FROM bridge_instances').all()).toEqual(before);read.close();}finally{for(const owner of owners)owner.closeNonforcing();f.input.destroy();f.output.destroy();}});
test('real HTTP listener can falsely report EXIT with owned native DB still open',async()=>{const f=fixture(),owners:BridgeStateStore[]=[],fences:RuntimeOperationFence[]=[];const p=BridgeStateStore.prototype.pinNonforcingShutdown,a=RuntimeOperationFence.prototype.assertAdmission;vi.spyOn(BridgeStateStore.prototype,'pinNonforcingShutdown').mockImplementation(function(this:BridgeStateStore){owners.push(this);return p.call(this);});vi.spyOn(RuntimeOperationFence.prototype,'assertAdmission').mockImplementation(function(this:RuntimeOperationFence){fences.push(this);return a.call(this);});const server=createHttpServer(f.config,upstream,catalog);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));await pause();let finish!:(v:any)=>void;const original={id:'held'},pending=fences[0].run(()=>new Promise(r=>finish=r));try{const initial=await server.closeNonforcing({allowSigkillEscalation:false,graceMs:20});expect(initial.outcome).toBe('timeout');expect(server.listening).toBe(false);finish(original);expect(await pending).toBe(original);await pause();console.log('http-late-observe',server.observeNonforcingExit(),'db-open',(owners[0] as any).database.open,'db-observe',owners[0].observeNonforcingExit());expect(server.observeNonforcingExit().exited).toBe(true);expect((owners[0] as any).database.open).toBe(false);expect(owners[0].observeNonforcingExit().exited).toBe(true);expect(initial.outcome).toBe('timeout');}finally{finish?.(original);await pending;for(const owner of owners)owner.closeNonforcing();f.input.destroy();f.output.destroy();}});
