// Retained exact 019b539 independent assertions; imports adapted; owned-DB final assertion requires actual close under the new continuation contract. Original reviewer source remains frozen.
import {test,expect,vi,afterEach} from 'vitest';
import {RuntimeOperationFence} from '../src/runtimeOperationFence.js';
import {McpEventsController} from '../src/mcpEvents.js';
import {loadConfig} from '../src/config.js';
import {EventDestinationVault} from '../src/mcpWebhook.js';
import {InMemoryTelemetryService} from '../src/telemetryService.js';
import {installMcpOperationFence} from '../src/server.js';
import {shutdownResult} from '../src/shutdown.js';
import {PassThrough} from 'node:stream';
import {createStdioBridgeRuntime} from '../src/stdioServer.js';
import {BridgeStateStore} from '../src/stateStore.js';
import {CodexJobRegistry} from '../src/tools.js';
afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();});
const token='a'.repeat(64),secret='whsec_'+Buffer.alloc(32,1).toString('base64');
function eventFixture(sender:any){const config=loadConfig({CODEX_MCP_BRIDGE_TOKEN:token,CODEX_MCP_BRIDGE_EVENTS_ENABLED:'1',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:process.env.TMPDIR+'/unused.sqlite'});const vault=new EventDestinationVault(token),id='owned-record';const record:any={jobId:'job',id,revision:1,expiresAt:Date.now()+60000,delivery:'pending',nextAttemptAt:0,attempts:0,scopeId:'scope',event:{eventId:'original-event'},destination:vault.seal(id,{url:'https://example.com/events',secret})};const ledger={maintain:vi.fn(),list:vi.fn(()=>[record]),get:vi.fn(()=>record),save:vi.fn(()=>true),enqueue:vi.fn()};const jobs:any={subscribeChanges:()=>vi.fn(),admissionStateStore:{mcpEvents:ledger},activityTransaction:(f:any)=>f()};const c:any=new McpEventsController(config,jobs,{require:()=>({scopeId:'scope'})} as any,sender);record.principal=c.principal;c.requireJob=()=>({jobId:'job'});const context:any={http:{authInfo:{scopes:['bridge'],extra:{bridgeMcpPrincipal:c.principal}}},mcpReq:{_meta:{},signal:new AbortController().signal}};return {c,ledger,record,context};}
test('native async original rejection identity is preserved',async()=>{const f=new RuntimeOperationFence(),error={original:true};const p=f.run(()=>Promise.reject(error));await expect(p).rejects.toBe(error);f.pinNonforcingShutdown();expect(f.observeNonforcingExit().exited).toBe(true);});
test('native Promise subclass cannot execute species or then during admission',async()=>{let reads=0;class P extends Promise<any>{static get [Symbol.species](){reads++;return Promise;}}const p=new P(r=>r(2));const f=new RuntimeOperationFence();await expect(f.run(()=>p)).rejects.toThrow('UNCONFIRMED');f.pinNonforcingShutdown();expect(reads).toBe(0);expect(f.observeNonforcingExit().outcome).toBe('uncertain');});
test('nested unresolved native Promise counts original admission until rejection',async()=>{let reject!:(e:any)=>void;const e={id:2},f=new RuntimeOperationFence();const p=f.run(()=>new Promise((_,r)=>reject=r));f.pinNonforcingShutdown();expect(f.inFlight).toBe(1);reject(e);await expect(p).rejects.toBe(e);expect(f.inFlight).toBe(0);});
test('inherited then getter never executes',async()=>{let reads=0;const v=Object.create({get then(){reads++;return undefined;}}),f=new RuntimeOperationFence();await expect(f.run(()=>v)).rejects.toThrow('UNCONFIRMED');expect(reads).toBe(0);f.pinNonforcingShutdown();expect(f.observeNonforcingExit().outcome).toBe('uncertain');});
test('nested post-pin SDK request delegation is synchronously rejected at operation entry',async()=>{let h:any;const protocol:any={setRequestHandler(...a:any[]){h=a.at(-1);}};const f=new RuntimeOperationFence();installMcpOperationFence({server:protocol} as any,f);const receiver={r:3},result={same:true};protocol.setRequestHandler('x',{},function(this:any){expect(this).toBe(receiver);f.pinNonforcingShutdown();return result;});expect(await h.call(receiver)).toBe(result);await expect(h.call(receiver)).rejects.toThrow('PINNED');});
test('proxy return descriptor traps are never invoked',async()=>{let traps=0;const v=new Proxy({},{getPrototypeOf(){traps++;return null;},getOwnPropertyDescriptor(){traps++;return undefined;}}),f=new RuntimeOperationFence();await expect(f.run(()=>v)).rejects.toThrow('UNCONFIRMED');expect(traps).toBe(0);});
test('verification callback cannot execute body accessor after pin',async()=>{vi.useFakeTimers();let finish!:(v:any)=>void,reads=0;const f=eventFixture(()=>new Promise(r=>finish=r));f.ledger.get.mockReturnValue(undefined);const p=f.c.subscribe({arguments:{jobId:'job'},delivery:{url:'https://example.com/events',secret}},f.context);f.c.pinNonforcingShutdown();expect(f.c.observeNonforcingExit().outcome).toBe('timeout');finish({status:200,get body(){reads++;return '{}';}});await expect(p).rejects.toBeDefined();expect(f.ledger.save).not.toHaveBeenCalled();console.log('verification-accessor-reads',reads);expect(reads).toBe(0);});
test('post-pin sender rejection must retain the exact original failure',async()=>{vi.useFakeTimers();let reject!:(e:any)=>void;const error={original:'sender-rejection'},f=eventFixture(()=>new Promise((_,r)=>reject=r));await vi.advanceTimersByTimeAsync(0);f.c.pinNonforcingShutdown();reject(error);await vi.advanceTimersByTimeAsync(0);console.log('delivery-retained-rejection',f.c.retainedResponses.get(f.record.id));expect(f.c.retainedResponses.get(f.record.id)).toBe(error);});
test('owned DB cannot be omitted from later frontend EXIT observation',async()=>{const config=loadConfig({CODEX_MCP_BRIDGE_NO_AUTH:'1',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:process.env.TMPDIR+'/review-owned-request.sqlite'});const owners:BridgeStateStore[]=[];const orig=BridgeStateStore.prototype.pinNonforcingShutdown;vi.spyOn(BridgeStateStore.prototype,'pinNonforcingShutdown').mockImplementation(function(this:BridgeStateStore){owners.push(this);return orig.call(this);});const fences:RuntimeOperationFence[]=[];const admit=RuntimeOperationFence.prototype.assertAdmission;vi.spyOn(RuntimeOperationFence.prototype,'assertAdmission').mockImplementation(function(this:RuntimeOperationFence){fences.push(this);return admit.call(this);});const input=new PassThrough(),output=new PassThrough();const runtime=createStdioBridgeRuntime(config,{listTools:async()=>({tools:[]}),callTool:async()=>({content:[]}),close:async()=>{}} as any,{input,output,modelCatalog:{getCatalog:async()=>({})} as any});await new Promise(r=>setTimeout(r,20));let finish!:(v:any)=>void;const original={same:true},pending=fences[0].run(()=>new Promise(r=>finish=r));try{const initial=await runtime.closeNonforcing({allowSigkillEscalation:false,graceMs:30});expect(initial.outcome).toBe('timeout');const owner=owners[0];expect((owner as any).database.open).toBe(true);finish(original);expect(await pending).toBe(original);console.log('late-observation',runtime.observeNonforcingExit(),'owned-open',(owner as any).database.open,'owned-observation',owner.observeNonforcingExit());expect(runtime.observeNonforcingExit().exited).toBe(true);expect((owner as any).database.open).toBe(false);expect(owner.observeNonforcingExit().exited).toBe(true);expect(initial.outcome).toBe('timeout');}finally{finish?.(original);await pending;for(const owner of owners)owner.closeNonforcing();input.destroy();output.destroy();}});
test('event worker publishes owned in-flight token before synchronous ledger reentry',async()=>{vi.useFakeTimers();const f=eventFixture(async()=>({status:200}));let during:any;f.ledger.maintain.mockImplementation(()=>{f.c.pinNonforcingShutdown();during=f.c.observeNonforcingExit();});await vi.advanceTimersByTimeAsync(0);console.log('event-maintain-reentry-observation',during);expect(during.exited).toBe(false);});
test('event ledger failure at pin cannot disappear into successful event receipt',async()=>{vi.useFakeTimers();const error={original:'ledger-failure'},f=eventFixture(async()=>({status:200}));f.ledger.maintain.mockImplementation(()=>{f.c.pinNonforcingShutdown();throw error;});await vi.advanceTimersByTimeAsync(0);console.log('event-maintain-failure-observation',f.c.observeNonforcingExit());expect(f.c.observeNonforcingExit().outcome).toBe('uncertain');});
test('memory descriptor reentry is counted and prevents later descriptor delegation',async()=>{const service:any=new InMemoryTelemetryService();let calls=0,during:any;const record=new Proxy({component:'state',metric:'duration',durationMs:1},{getOwnPropertyDescriptor(target,key){calls++;service.pinNonforcingShutdown();during=service.observeNonforcingExit();return Reflect.getOwnPropertyDescriptor(target,key);}});expect(service.recordRuntimeMeasurement(record)).toBe(false);expect(calls).toBe(1);expect(during.outcome).toBe('uncertain');expect(service.callbacksInFlight).toBe(0);expect(service.observeNonforcingExit().outcome).toBe('uncertain');});
test('cyclic memory record keeps UNKNOWN after otherwise empty closure',async()=>{const service=new InMemoryTelemetryService();const value:any={severity:'info',component:'state',code:'review.cyclic'};value.details=value;expect(service.recordDiagnosticEvent(value)).toBe(false);expect((await service.closeNonforcing({allowSigkillEscalation:false,graceMs:0})).outcome).toBe('uncertain');expect(service.recordDiagnosticEvent({severity:'info',component:'state',code:'late'})).toBe(false);expect(service.observeNonforcingExit().outcome).toBe('uncertain');});
test('memory transport admission copies original data and does not retain writable source',async()=>{const service=new InMemoryTelemetryService(),input:any={kind:'status-wait-aborted',reasonCode:'review.original'};const result=service.recordTransportObservation(input,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');expect(result).toBeDefined();input.reasonCode='mutated';expect(service.listTransportObservations()[0].reasonCode).toBe('review.original');expect((await service.closeNonforcing({allowSigkillEscalation:false,graceMs:0})).exited).toBe(true);});

test.each(['constructor','then'])('sender native Promise %s accessor cannot run after synchronous pin',async key=>{
 vi.useFakeTimers();let reads=0,f:any;
 const raw=Promise.resolve({status:200,body:'original'});
 Object.defineProperty(raw,key,{get(){reads++;return key==='constructor'?Promise:undefined;}});
 f=eventFixture(()=>{f.c.pinNonforcingShutdown();return raw;});
 await vi.advanceTimersByTimeAsync(0);
 expect(reads).toBe(0);expect(f.c.senderFence.inFlight).toBe(1);
 expect(f.c.observeNonforcingExit().outcome).toBe('uncertain');
 expect(f.ledger.save).toHaveBeenCalledOnce();
});

test('event unsubscribe failure preserves original failure without reading message',()=>{
 vi.useFakeTimers();let reads=0;const raw=Object.defineProperty({},'message',{get(){reads++;return 'late';}});
 const f=eventFixture(async()=>({status:200}));f.c.unsubscribe=()=>{throw raw;};
 f.c.pinNonforcingShutdown();expect(reads).toBe(0);expect(f.c.retainedErrors.get('unsubscribe')).toBe(raw);
 expect(f.c.observeNonforcingExit().outcome).toBe('uncertain');
});
