import {test,expect,vi} from 'vitest';
import {RuntimeOperationFence} from '../src/runtimeOperationFence.js';
test('quiescence receipt requires an explicit permanent pin',async()=>{const owner=new RuntimeOperationFence();expect(owner.observeNonforcingExit().outcome).toBe('uncertain');expect(await owner.run(()=>3)).toBe(3);owner.pinNonforcingShutdown();expect(owner.observeNonforcingExit().exited).toBe(true);const run=vi.fn();await expect(owner.run(run)).rejects.toThrow('RUNTIME_NONFORCING_PINNED');expect(run).not.toHaveBeenCalled();});
test('pending owned callback retains original settlement until physically complete',async()=>{const owner=new RuntimeOperationFence();let finish!:(v:object)=>void;const original={original:true};const promise=owner.run(()=>new Promise<object>(r=>finish=r));owner.pinNonforcingShutdown();expect(owner.inFlight).toBe(1);expect(owner.observeNonforcingExit().outcome).toBe('timeout');finish(original);expect(await promise).toBe(original);expect(owner.observeNonforcingExit().exited).toBe(true);});
test('callback reentry pins before a second callback can delegate',async()=>{const owner=new RuntimeOperationFence(),late=vi.fn();const observed=owner.run(()=>{owner.pinNonforcingShutdown();void owner.run(late).catch(()=>{});expect(owner.observeNonforcingExit().outcome).toBe('timeout');return 'original';});expect(await observed).toBe('original');expect(late).not.toHaveBeenCalled();expect(owner.observeNonforcingExit().exited).toBe(true);});
test('original rejection is preserved while in-flight observation clears',async()=>{const owner=new RuntimeOperationFence();let fail!:(e:Error)=>void;const original=new Error('original');const promise=owner.run(()=>new Promise<void>((_r,reject)=>fail=reject));owner.pinNonforcingShutdown();expect(owner.observeNonforcingExit().outcome).toBe('timeout');fail(original);let error:unknown;try{await promise;}catch(e){error=e;}expect(error).toBe(original);expect(owner.observeNonforcingExit().exited).toBe(true);});
test('ordinary-close history and invalid observations cannot become positive quiescence',async()=>{for(const mutate of [(o:RuntimeOperationFence)=>o.markOrdinaryClose(),(o:RuntimeOperationFence)=>o.invalidateObservation()]){const owner=new RuntimeOperationFence();mutate(owner);owner.pinNonforcingShutdown();await expect(owner.run(()=>1)).rejects.toThrow();expect(owner.observeNonforcingExit().outcome).toBe('uncertain');}});

test('native Promise constructor accessors never execute at the operation boundary',async()=>{const owner=new RuntimeOperationFence();let reads=0;const raw=Promise.resolve('original');Object.defineProperty(raw,'constructor',{get(){reads++;owner.pinNonforcingShutdown();return Promise;}});await expect(owner.run(()=>raw)).rejects.toThrow('RESULT_UNCONFIRMED');expect(reads).toBe(0);owner.pinNonforcingShutdown();expect(owner.observeNonforcingExit().outcome).toBe('uncertain');expect(owner.inFlight).toBe(1);});
test('thenable accessors and Proxy traps cannot delegate after callback pin',async()=>{for(const proxy of [false,true]){const owner=new RuntimeOperationFence();let reads=0;const value=proxy?new Proxy({}, {getOwnPropertyDescriptor(){reads++;return undefined;},getPrototypeOf(){reads++;return Object.prototype;},get(){reads++;return undefined;}}):Object.defineProperty({},'then',{get(){reads++;return ()=>{};}});await expect(owner.run(()=>{owner.pinNonforcingShutdown();return value;})).rejects.toThrow('RESULT_UNCONFIRMED');expect(reads).toBe(0);expect(owner.observeNonforcingExit().outcome).toBe('uncertain');expect(owner.inFlight).toBe(1);}});
