import {test,expect,vi,afterEach} from 'vitest';
import {RuntimeOperationFence} from '../src/runtimeOperationFence.js';
import {McpEventsController} from '../src/mcpEvents.js';
import {loadConfig} from '../src/config.js';
afterEach(()=>{vi.restoreAllMocks();vi.useRealTimers();});
for(const [index,value] of [undefined,null,17,'plain',true,{original:1},Object.assign(Object.create(null),{data:1})].entries())test('fresh sync standard value preserves identity '+index,()=>{const f=new RuntimeOperationFence();expect(f.runSynchronous(()=>value)).toBe(value);f.pinNonforcingShutdown();expect(f.observeNonforcingExit().exited).toBe(true);});
test('fresh sync reentrant pin remains active and blocks nested admission',()=>{const f=new RuntimeOperationFence(),value={same:true};let during:any;expect(f.runSynchronous(()=>{f.pinNonforcingShutdown();during=f.observeNonforcingExit();expect(()=>f.runSynchronous(()=>0)).toThrow('PINNED');return value;})).toBe(value);expect(during.outcome).toBe('timeout');expect(f.observeNonforcingExit().exited).toBe(true);});
test('fresh sync original thrown object preserves exact caller rejection',()=>{const f=new RuntimeOperationFence(),raw={original:'sync-throw'};let caught;try{f.runSynchronous(()=>{throw raw;});}catch(error){caught=error;}expect(caught).toBe(raw);expect(f.inFlight).toBe(0);});
test('fresh strict native sync Promise rejection retains raw and exact error',async()=>{const f:any=new RuntimeOperationFence(),error={original:'native-sync-rejection'},raw=Promise.reject(error);expect(()=>f.runSynchronous(()=>raw)).toThrow('UNCONFIRMED');await Promise.resolve();await Promise.resolve();f.pinNonforcingShutdown();const values=[...f.active.values()];expect(values.some((x:any)=>x.value===raw&&x.error===error)).toBe(true);expect(f.observeNonforcingExit().outcome).toBe('uncertain');});
test('fresh sync own then accessor is never invoked and is retained',()=>{let reads=0;const raw={get then(){reads++;throw Error('should-not-run');}},f:any=new RuntimeOperationFence();expect(()=>f.runSynchronous(()=>raw)).toThrow('UNCONFIRMED');expect(reads).toBe(0);expect([...f.active.values()].some(value=>value===raw)).toBe(true);f.pinNonforcingShutdown();expect(f.observeNonforcingExit().outcome).toBe('uncertain');});
test('fresh sync inherited then accessor is never invoked',()=>{let reads=0;const raw=Object.create({get then(){reads++;return Promise.prototype.then;}}),f=new RuntimeOperationFence();expect(()=>f.runSynchronous(()=>raw)).toThrow('UNCONFIRMED');expect(reads).toBe(0);});
test('fresh sync proxy result invokes no descriptor/prototype traps',()=>{let traps=0;const raw=new Proxy({},{getPrototypeOf(){traps++;return null;},getOwnPropertyDescriptor(){traps++;return undefined;}}),f=new RuntimeOperationFence();expect(()=>f.runSynchronous(()=>raw)).toThrow('UNCONFIRMED');expect(traps).toBe(0);});
test('fresh sync Promise subclass invokes no custom species or then',()=>{let reads=0;class P extends Promise<any>{static get [Symbol.species](){reads++;return Promise;}}const raw=new P(r=>r(1)),f=new RuntimeOperationFence();expect(()=>f.runSynchronous(()=>raw)).toThrow('UNCONFIRMED');expect(reads).toBe(0);});
test('fresh unchanged async original Promise settlement and rejection stay exact',async()=>{const f=new RuntimeOperationFence(),value={same:'async'},error={same:'reject'};expect(await f.run(()=>Promise.resolve(value))).toBe(value);await expect(f.run(()=>Promise.reject(error))).rejects.toBe(error);f.pinNonforcingShutdown();expect(f.observeNonforcingExit().exited).toBe(true);});
test('fresh sync ordinary history remains sticky across new observations',()=>{const f=new RuntimeOperationFence();f.markOrdinaryClose();f.runSynchronous(()=>undefined);f.pinNonforcingShutdown();f.pinNonforcingShutdown();expect(f.observeNonforcingExit().outcome).toBe('uncertain');});
function receiverFixture(){let c:any;const receivers:any[]=[];const config=loadConfig({CODEX_MCP_BRIDGE_TOKEN:'a'.repeat(64),CODEX_MCP_BRIDGE_EVENTS_ENABLED:'1',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:process.env.TMPDIR+'/review-6e7f9fd-receiver-unused.sqlite'}),jobs:any={subscribeChanges(){return function(this:any){receivers.push(this);};},admissionStateStore:{mcpEvents:{maintain(){},list(){return [];}}}};c=new McpEventsController(config,jobs,{require:()=>({scopeId:'scope'})} as any,async()=>({status:200}));return {c,receivers};}
test('fresh captured callback receiver matches existing ordinary invocation',async()=>{vi.useFakeTimers();const ordinary=receiverFixture(),nonforcing=receiverFixture();await ordinary.c.close();nonforcing.c.pinNonforcingShutdown();console.log('captured-receiver',{ordinaryIsController:ordinary.receivers[0]===ordinary.c,nonforcingIsController:nonforcing.receivers[0]===nonforcing.c,nonforcingReceiverUndefined:nonforcing.receivers[0]===undefined});expect(ordinary.receivers[0]).toBe(ordinary.c);expect(nonforcing.receivers[0]).toBe(nonforcing.c);});
