import {test,expect,vi} from 'vitest';import {randomUUID} from 'node:crypto';import {appendFileSync} from 'node:fs';import {dirname,join} from 'node:path';
import {CodexJobRegistry} from '../src/tools.js';import {BridgeStateStore} from '../src/stateStore.js';import {snapshotNonforcingData} from '../src/nonforcingData.js';
const result:any={content:[{type:'text',text:'retained-original'}],structuredContent:{threadId:'review-thread'}};
function input(){return {operation:'start' as const,cwd:process.cwd(),sandbox:'read-only' as const,scopeId:randomUUID(),requestId:randomUUID(),requestHash:'a'.repeat(64),requestHashVersion:2 as const,exclusiveKeys:[],sessionDecision:{requestedMode:'new' as const,action:'start' as const,reason:'explicit-new' as const}};}
function record(_label:string,_data:unknown){}
function fixture(options:any={}){const state=new BridgeStateStore({file:':memory:'});const jobs=new CodexJobRegistry({stateStore:state,allowedRoots:[process.cwd()],...options});return {state,jobs};}
function upstream(ack:any=vi.fn()){return {listTools:async()=>({tools:[]}),callTool:async()=>result,close:async()=>{},supportsExecutionRecovery:()=>true,acknowledgeExecution:ack};}
import {registerBridgeTools} from '../src/tools.js';import {loadConfig} from '../src/config.js';import {SessionRegistry} from '../src/sessionRegistry.js';import {UserSettingsStore} from '../src/userSettings.js';import {ScopeResolver} from '../src/scopeResolver.js';

function application(){const f=fixture({projectionOnly:true});const config=loadConfig({HOME:process.env.HOME,CODEX_MCP_BRIDGE_NO_AUTH:'1',CODEX_MCP_BRIDGE_ROOTS:process.cwd(),CODEX_MCP_BRIDGE_CODEX:'/usr/bin/false',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:join(process.env.HOME!,'not-opened.sqlite')});const settings=new UserSettingsStore(config,{stateStore:f.state});const sessions=new SessionRegistry({stateStore:f.state,allowedRoots:[process.cwd()]});const resolver=new ScopeResolver({stateStore:f.state});const catalog:any={getCatalog:async()=>({models:[],source:'fixture',fetchedAt:new Date().toISOString(),fingerprint:'a'.repeat(64),cached:false,stale:false,validation:'valid'})};const server:any={registerResource:()=>({}),registerTool:()=>({})};const u:any=upstream();const registered=registerBridgeTools(server,config,u,sessions,f.jobs,catalog,settings,resolver);return {...f,settings,catalog,registered,u};}




test.each(['false','promise','throw'])('NEW unsupported terminal application observer %s cannot ACK or lose original settlement',async kind=>{
 const f=application();const ack=vi.fn();f.u.acknowledgeExecution=ack;let job:any,calls=0,resolve:any;const raw:any=kind==='false'?false:kind==='promise'?new Promise(r=>resolve=r):{raw:'observer-error'};let reads=0;Object.defineProperty(kind==='throw'?raw:{},'message',{get(){reads++;throw Error('must not format');}});const unsub=f.registered.applicationService.subscribeChanges(()=>{if(job?.status==='completed'){calls++;if(kind==='throw')throw raw;return raw;}});
 try{job=f.jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});return result;});const id=job.jobId,p=job.promise;await p;f.jobs.pinNonforcingShutdown();const all=[...(f.jobs as any).nonforcingLateObservations.values()].flat();record('observer-unsupported-'+kind,{calls,reads,ackCalls:ack.mock.calls.length,rawRetained:all.some((x:any)=>x.value===raw),originalResult:(f.jobs as any).deferredSettlements.get(id)?.result===result,resource:f.jobs.observeNonforcingExit()});expect(reads).toBe(0);expect(all.some((x:any)=>x.value===raw)).toBe(true);expect(f.jobs.observeNonforcingExit().outcome).toBe('uncertain');expect(ack).not.toHaveBeenCalled();expect((f.jobs as any).deferredSettlements.get(id)?.result).toBe(result);}finally{resolve?.();unsub();f.registered.dispose();f.state.close();}
});
test.each(['worker','map-delete'])('NEW throwing terminal observer %s contradiction still blocks ACK',async kind=>{
 const f=application();const ack=vi.fn();f.u.acknowledgeExecution=ack;let job:any,calls=0;const raw={original:'thrown-error'};const unsub=f.registered.applicationService.subscribeChanges(()=>{if(job?.status==='completed'&&calls===0){calls++;if(kind==='worker'){job.workerId='throw-observer-worker';job.workerGeneration=99;}else(f.jobs as any).jobs.delete(job.jobId);throw raw;}});
 try{job=f.jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});return result;});const id=job.jobId,p=job.promise;await p;f.jobs.pinNonforcingShutdown();record('observer-throw-'+kind,{calls,ackCalls:ack.mock.calls.length,worker:job.workerId,sqlWorker:f.state.listJobs()[0].workerId,indexRetained:(f.jobs as any).jobs.get(id)===job,perJobUnknown:(f.jobs as any).unconfirmedJobCallbacks.has(job),originalResult:(f.jobs as any).deferredSettlements.get(id)?.result===result,resource:f.jobs.observeNonforcingExit()});expect(calls).toBe(1);expect(ack).not.toHaveBeenCalled();expect((f.jobs as any).unconfirmedJobCallbacks.has(job)).toBe(true);expect((f.jobs as any).deferredSettlements.get(id)?.result).toBe(result);}finally{unsub();f.registered.dispose();f.state.close();}
});
test('NEW throwing undo retains exact original capability along with original error',async()=>{
 const {state,jobs}=fixture();jobs.attachUpstream(upstream());const upsert=state.upsertJob.bind(state);let conflict=false;state.upsertJob=((j:any)=>{if(j.status==='completed'&&!conflict){conflict=true;throw Error('private terminal conflict');}return upsert(j);}) as any;const raw={raw:'undo-failure'};const undo=vi.fn(()=>{throw raw;});
 try{const job=jobs.start(input(),async()=>result,()=>undo);const id=job.jobId;await job.promise;jobs.pinNonforcingShutdown();const obs=(jobs as any).nonforcingLateObservations.get(id)||[];record('invoked-undo-throw',{undoCalls:undo.mock.calls.length,errorRetained:obs.some((x:any)=>x.value===raw),capabilityRetained:obs.some((x:any)=>x.value===undo),originalResult:(jobs as any).deferredSettlements.get(id)?.result===result,resource:jobs.observeNonforcingExit()});expect(undo).toHaveBeenCalledOnce();expect(obs.some((x:any)=>x.value===raw)).toBe(true);expect((jobs as any).deferredSettlements.get(id)?.result).toBe(result);expect(obs.some((x:any)=>x.value===undo)).toBe(true);}finally{state.close();}
});
test.each(['promise','descriptor','prototype','map-replace'])('NEW supported void observer %s mutation retains original owned identity and blocks ACK',async kind=>{
 const {state,jobs}=fixture();const ack=vi.fn();jobs.attachUpstream(upstream(ack));let job:any,calls=0,reads=0,p:any,proto:any,descriptor:any;const unsub=jobs.subscribeChanges(()=>{if(job?.status==='completed'&&calls===0){calls++;if(kind==='promise')job.promise=Promise.resolve();else if(kind==='descriptor')Object.defineProperty(job,'version',{get(){reads++;return 99;},configurable:true,enumerable:true});else if(kind==='prototype')Object.setPrototypeOf(job,{unsupported:true});else(jobs as any).jobs.set(job.jobId,{...job});}});
 try{job=jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});return result;});p=job.promise;proto=Object.getPrototypeOf(job);descriptor=Object.getOwnPropertyDescriptor(job,'version');const id=job.jobId;await p;jobs.pinNonforcingShutdown();expect(calls).toBe(1);expect(reads).toBe(0);expect(ack).not.toHaveBeenCalled();expect((jobs as any).deferredSettlements.get(id)?.result).toBe(result);expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{unsub();if(job){Object.setPrototypeOf(job,proto);Object.defineProperty(job,'version',descriptor);}state.close();}
});
test('NEW observer pin then native Promise return retains exact raw owner and prevents next observer',async()=>{
 const {state,jobs}=fixture();const ack=vi.fn();jobs.attachUpstream(upstream(ack));let job:any,resolve:any;const raw=new Promise(r=>resolve=r);const later=vi.fn();jobs.subscribeChanges(()=>{if(job?.status==='completed'){jobs.pinNonforcingShutdown();return raw;}});jobs.subscribeChanges(()=>{if(job?.status==='completed')later();});try{job=jobs.start(input(),async()=>result);await job.promise;expect(later).not.toHaveBeenCalled();expect(ack).not.toHaveBeenCalled();expect([...(jobs as any).nonforcingLateObservations.values()].flat().some((x:any)=>x.value===raw)).toBe(true);expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{resolve();state.close();}
});
test.each(['waiter','terminal','scope'])('NEW %s notification callback authority mutation is fenced',async kind=>{
 const {state,jobs}=fixture();const ack=vi.fn();jobs.attachUpstream(upstream(ack));let finish:any;const raw=new Promise<any>(r=>finish=r);try{const job=jobs.start(input(),async()=>raw);const id=job.jobId,p=job.promise;const callback=()=>{if(job.status==='completed')job.workerId='waiter-worker';};if(kind==='waiter')(jobs as any).waiters.set(id,new Set([callback]));else if(kind==='terminal')(jobs as any).terminalWaiters.set(id,new Set([callback]));else(jobs as any).scopeWaiters.set(job.scopeId,new Set([callback]));finish(result);await p;jobs.pinNonforcingShutdown();expect(ack).not.toHaveBeenCalled();expect((jobs as any).deferredSettlements.get(id)?.result).toBe(result);expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{finish?.(result);state.close();}
});
test('NEW ordinary read-only application observer preserves original worker and ACK',async()=>{
 const f=application();const ack=vi.fn();f.u.acknowledgeExecution=ack;let job:any,calls=0;const unsub=f.registered.applicationService.subscribeChanges(()=>{if(job?.status==='completed'){calls++;void job.workerId;}});try{job=f.jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});return result;});await job.promise;expect(calls).toBeGreaterThanOrEqual(1);expect(ack).toHaveBeenCalledOnce();f.jobs.pinNonforcingShutdown();expect(f.jobs.observeNonforcingExit().exited).toBe(true);}finally{unsub();f.registered.dispose();f.state.close();}
});
