// Retained 19c6056 independent reproducers; observation sink only adapted.
import {test,expect,vi} from 'vitest';import {randomUUID} from 'node:crypto';import {appendFileSync} from 'node:fs';import {dirname,join} from 'node:path';
import {CodexJobRegistry} from '../src/tools.js';import {BridgeStateStore} from '../src/stateStore.js';import {snapshotNonforcingData} from '../src/nonforcingData.js';
const result:any={content:[{type:'text',text:'retained-original'}],structuredContent:{threadId:'review-thread'}};
function input(){return {operation:'start' as const,cwd:process.cwd(),sandbox:'read-only' as const,scopeId:randomUUID(),requestId:randomUUID(),requestHash:'a'.repeat(64),requestHashVersion:2 as const,exclusiveKeys:[],sessionDecision:{requestedMode:'new' as const,action:'start' as const,reason:'explicit-new' as const}};}
function record(_label:string,_data:unknown){}
function fixture(options:any={}){const state=new BridgeStateStore({file:':memory:'});const jobs=new CodexJobRegistry({stateStore:state,allowedRoots:[process.cwd()],...options});return {state,jobs};}
function upstream(ack:any=vi.fn()){return {listTools:async()=>({tools:[]}),callTool:async()=>result,close:async()=>{},supportsExecutionRecovery:()=>true,acknowledgeExecution:ack};}
import {registerBridgeTools} from '../src/tools.js';import {loadConfig} from '../src/config.js';import {SessionRegistry} from '../src/sessionRegistry.js';import {UserSettingsStore} from '../src/userSettings.js';import {ScopeResolver} from '../src/scopeResolver.js';

test.each([false,{unconfirmed:true},'unexpected'])('new native ACK fulfilled nonvoid %j cannot certify quiet',async returned=>{
 const {state,jobs}=fixture();const p=Promise.resolve(returned);jobs.attachUpstream(upstream(()=>p));
 try{const job=jobs.start(input(),async()=>result);await job.promise;await Promise.resolve();jobs.pinNonforcingShutdown();record('ack-fulfilled-'+typeof returned,{status:job.status,resource:jobs.observeNonforcingExit(),retained:(jobs as any).executionAcknowledgements.has(job),observations:(jobs as any).nonforcingLateObservationCount});expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test('new completion callback pin stops all subsequent live Job getter evaluation',async()=>{
 const {state,jobs}=fixture();let reads=0;let job:any;const callback=(_result:any,current:any)=>{jobs.pinNonforcingShutdown();Object.defineProperty(current,'version',{enumerable:true,configurable:true,get(){reads++;return 1;}});};
 try{job=jobs.start(input(),async()=>result,callback);await job.promise;record('completion-job-getter',{reads,status:job.status,sql:state.listJobs()[0].status,resource:jobs.observeNonforcingExit()});expect(reads).toBe(0);}finally{if(job)Object.defineProperty(job,'version',{value:1,writable:true,configurable:true,enumerable:true});state.close();}
});
test.each(['normal','upstream-error'])('new completion %s exception formatting never evaluates original message getter after pin',async kind=>{
 const {state,jobs}=fixture();let reads=0;const error=new Error();Object.defineProperty(error,'message',{get(){reads++;return 'arbitrary original accessor';}});const returned:any=kind==='normal'?result:{...result,isError:true};
 try{const job=jobs.start(input(),async()=>returned,()=>{jobs.pinNonforcingShutdown();throw error;});await job.promise;record('completion-error-getter-'+kind,{reads,status:job.status,sql:state.listJobs()[0].status,resource:jobs.observeNonforcingExit(),retainsOriginal:(jobs as any).nonforcingLateObservations.get(job.jobId)?.some((r:any)=>r.value===error)});expect(reads).toBe(0);}finally{state.close();}
});
function application(){const f=fixture({projectionOnly:true});const config=loadConfig({HOME:process.env.HOME,CODEX_MCP_BRIDGE_NO_AUTH:'1',CODEX_MCP_BRIDGE_ROOTS:process.cwd(),CODEX_MCP_BRIDGE_CODEX:'/usr/bin/false',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:join(process.env.HOME!,'not-opened.sqlite')});const settings=new UserSettingsStore(config,{stateStore:f.state});const sessions=new SessionRegistry({stateStore:f.state,allowedRoots:[process.cwd()]});const resolver=new ScopeResolver({stateStore:f.state});const catalog:any={getCatalog:async()=>({models:[],source:'fixture',fetchedAt:new Date().toISOString(),fingerprint:'a'.repeat(64),cached:false,stale:false,validation:'valid'})};const server:any={registerResource:()=>({}),registerTool:()=>({})};const u:any=upstream();const registered=registerBridgeTools(server,config,u,sessions,f.jobs,catalog,settings,resolver);return {...f,settings,catalog,registered};}
test.each(['false','promise'])('new internal application subscription %s result remains original callback uncertainty',async kind=>{
 const {state,jobs,registered}=application();let release!:()=>void,calls=0;const p=new Promise<void>(r=>release=r);let unsubscribe:any;
 try{unsubscribe=registered.applicationService.subscribeChanges!((()=>{calls++;return kind==='false'?false:p;}) as any);jobs.createAgent({scopeId:randomUUID(),agentName:'original'});jobs.pinNonforcingShutdown();record('application-listener-'+kind,{calls,resource:jobs.observeNonforcingExit(),observations:(jobs as any).nonforcingLateObservationCount});expect(calls).toBe(1);expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{release();await p;unsubscribe?.();registered.dispose();state.close();}
});
test('new application subscription model getter pin stops returned registration callable',()=>{
 const {state,jobs,catalog,registered}=application();let reads=0,calls=0,unsubscribe:any;Object.defineProperty(catalog,'subscribe',{get(){reads++;jobs.pinNonforcingShutdown();return ()=>{calls++;return ()=>{};};}});
 try{let error:any;try{unsubscribe=registered.applicationService.subscribeChanges!(()=>{});}catch(e){error=e;}record('application-subscribe-getter',{reads,calls,errorType:typeof error,resource:jobs.observeNonforcingExit()});expect(calls).toBe(0);}finally{unsubscribe?.();registered.dispose();state.close();}
});
test.each(['own-descriptor','prototype'])('new ACK proxy %s pin stops further inspection and native delegation',async kind=>{
 const {state,jobs}=fixture();let prototypes=0;const p=new Proxy(Promise.resolve(),{getOwnPropertyDescriptor(t,k){if(kind==='own-descriptor')jobs.pinNonforcingShutdown();return Reflect.getOwnPropertyDescriptor(t,k);},getPrototypeOf(t){prototypes++;if(kind==='prototype')jobs.pinNonforcingShutdown();return Reflect.getPrototypeOf(t);}});jobs.attachUpstream(upstream(()=>p));
 try{const job=jobs.start(input(),async()=>result);await job.promise;expect(prototypes).toBe(kind==='own-descriptor'?0:1);expect((jobs as any).executionAcknowledgements.get(job)?.value).toBe(p);expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test('new intrinsic native ACK observation never reads own then accessor',async()=>{
 const {state,jobs}=fixture();let reads=0;const p=Promise.resolve();Object.defineProperty(p,'then',{get(){reads++;throw Error('no lookup');}});jobs.attachUpstream(upstream(()=>p));
 try{const job=jobs.start(input(),async()=>result);await job.promise;await Promise.resolve();expect(reads).toBe(0);jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().exited).toBe(true);}finally{state.close();}
});
test('new native ACK subclass preserves original identity as unqualified',async()=>{
 const {state,jobs}=fixture();class Other extends Promise<void>{};const p=new Other(r=>r());jobs.attachUpstream(upstream(()=>p));
 try{const job=jobs.start(input(),async()=>result);await job.promise;jobs.pinNonforcingShutdown();expect((jobs as any).executionAcknowledgements.get(job)?.value).toBe(p);expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test('new mutated intrinsic Promise descriptor is refused without getter invocation',()=>{
 const {state,jobs}=fixture();const original=Object.getOwnPropertyDescriptor(Promise,Symbol.species)!;let reads=0;try{Object.defineProperty(Promise,Symbol.species,{get(){reads++;return Promise;},configurable:true});expect((jobs as any).safeAcknowledgementPromise(Promise.resolve())).toBe(false);expect(reads).toBe(0);}finally{Object.defineProperty(Promise,Symbol.species,original);state.close();}
});
test.each(['false','throw'])('new upstream-failure undo %s retains original resolved outcome and exact undo uncertainty',async kind=>{
 const {state,jobs}=fixture();const upsert=state.upsertJob.bind(state);let conflict=false,receiver:any='notcalled',reads=0;const original=new Error('original undo');state.upsertJob=((job:any)=>{if(!conflict&&job.status==='failed'){conflict=true;throw new Error('fixture conflict');}return upsert(job);}) as any;const undo:any=function(this:any){receiver=this;if(kind==='throw')throw original;return false;};Object.defineProperty(undo,'call',{get(){reads++;throw Error('poisoned');}});
 try{const job=jobs.start(input(),async()=>({...result,isError:true}),()=>undo);await job.promise;expect(receiver).toBeUndefined();expect(reads).toBe(0);expect(job.status).toBe('running');expect((jobs as any).deferredSettlements.get(job.jobId).kind).toBe('resolved');jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test('new valid assignment runtime and persistence retain ordinary identity and ACK',async()=>{
 const {state,jobs}=fixture();const ack=vi.fn();jobs.attachUpstream(upstream(ack));
 try{const job=jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original',workerGeneration:3,threadPersistence:'persistent',runtime:{codex:'1.2.3',sdk:'2.0.0',python:'3.14.0',channel:'stable',requestedAuthMode:'chatgpt',resolvedAuthMode:'api-key'}});return result;});await job.promise;expect(job.workerId).toBe('original');expect(job.threadPersistence).toBe('persistent');expect(job.runtime?.codex).toBe('1.2.3');expect(ack).toHaveBeenCalledOnce();jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().exited).toBe(true);}finally{state.close();}
});

test.each(['catalog','settings'])('internal %s notifications retain false and pending original returns',async topic=>{for(const kind of ['false','promise']){const f=application();let call!:()=>void,release!:()=>void;const original=new Promise<void>(r=>release=r);if(topic==='catalog')f.catalog.subscribe=(listener:()=>void)=>{call=listener;return ()=>{};};else f.settings.subscribeChanges=(listener:()=>void)=>{call=listener;return ()=>{};};const unsubscribe=f.registered.applicationService.subscribeChanges!((()=>kind==='false'?false:original) as any);try{call();f.jobs.pinNonforcingShutdown();expect(f.jobs.observeNonforcingExit().outcome).toBe('uncertain');expect([...(f.jobs as any).nonforcingLateObservations.get('application-listener')]).toContainEqual({kind:'listener-result',value:kind==='false'?false:original});}finally{release();await original;unsubscribe();f.registered.dispose();f.state.close();}}});
test('a subscription body pin retains cleanup instead of registering later catalog listeners',()=>{const f=application();const cleanup=vi.fn(),catalog=vi.fn();f.settings.subscribeChanges=()=>{f.jobs.pinNonforcingShutdown();return cleanup;};f.catalog.subscribe=catalog;try{expect(()=>f.registered.applicationService.subscribeChanges!(()=>{})).toThrow('SUBSCRIPTION_UNCONFIRMED');expect(cleanup).not.toHaveBeenCalled();expect(catalog).not.toHaveBeenCalled();expect(f.jobs.observeNonforcingExit().outcome).toBe('uncertain');expect([...(f.jobs as any).nonforcingLateObservations.get('application-subscription')]).toContainEqual({kind:'registration-result',value:cleanup});}finally{f.registered.dispose();f.state.close();}});
test('a pinned terminal callback cannot trigger replaced live Job identity getters',async()=>{const {state,jobs}=fixture();let reads=0;let job:any;try{job=jobs.start(input(),async()=>result,(_value,current)=>{jobs.pinNonforcingShutdown();Object.defineProperty(current,'jobId',{configurable:true,enumerable:true,get(){reads++;return 'untrusted';}});});await job.promise;expect(reads).toBe(0);expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{if(job)Object.defineProperty(job,'jobId',{configurable:true,enumerable:true,value:'restored-test-only',writable:true});state.close();}});
