import {test,expect,vi} from 'vitest';import {randomUUID} from 'node:crypto';import {appendFileSync} from 'node:fs';import {dirname,join} from 'node:path';
import {CodexJobRegistry} from '../src/tools.js';import {BridgeStateStore} from '../src/stateStore.js';import {snapshotNonforcingData} from '../src/nonforcingData.js';
const result:any={content:[{type:'text',text:'retained-original'}],structuredContent:{threadId:'review-thread'}};
function input(){return {operation:'start' as const,cwd:process.cwd(),sandbox:'read-only' as const,scopeId:randomUUID(),requestId:randomUUID(),requestHash:'a'.repeat(64),requestHashVersion:2 as const,exclusiveKeys:[],sessionDecision:{requestedMode:'new' as const,action:'start' as const,reason:'explicit-new' as const}};}
function record(_label:string,_data:unknown){}
function fixture(options:any={}){const state=new BridgeStateStore({file:':memory:'});const jobs=new CodexJobRegistry({stateStore:state,allowedRoots:[process.cwd()],...options});return {state,jobs};}
function upstream(ack:any=vi.fn()){return {listTools:async()=>({tools:[]}),callTool:async()=>result,close:async()=>{},supportsExecutionRecovery:()=>true,acknowledgeExecution:ack};}
import {registerBridgeTools} from '../src/tools.js';import {loadConfig} from '../src/config.js';import {SessionRegistry} from '../src/sessionRegistry.js';import {UserSettingsStore} from '../src/userSettings.js';import {ScopeResolver} from '../src/scopeResolver.js';

function application(){const f=fixture({projectionOnly:true});const config=loadConfig({HOME:process.env.HOME,CODEX_MCP_BRIDGE_NO_AUTH:'1',CODEX_MCP_BRIDGE_ROOTS:process.cwd(),CODEX_MCP_BRIDGE_CODEX:'/usr/bin/false',CODEX_MCP_BRIDGE_STATE_DATABASE_FILE:join(process.env.HOME!,'not-opened.sqlite')});const settings=new UserSettingsStore(config,{stateStore:f.state});const sessions=new SessionRegistry({stateStore:f.state,allowedRoots:[process.cwd()]});const resolver=new ScopeResolver({stateStore:f.state});const catalog:any={getCatalog:async()=>({models:[],source:'fixture',fetchedAt:new Date().toISOString(),fingerprint:'a'.repeat(64),cached:false,stale:false,validation:'valid'})};const server:any={registerResource:()=>({}),registerTool:()=>({})};const u:any=upstream();const registered=registerBridgeTools(server,config,u,sessions,f.jobs,catalog,settings,resolver);return {...f,settings,catalog,registered};}


test.each(['normal','upstream-error','rejected'])('NEW %s committed-store worker authority mutation cannot be silently overwritten',async kind=>{
 let jobs:any,job:any,armed=false,mutations=0;const state=new BridgeStateStore({file:':memory:',onTransactionCommitted:()=>{if(!armed || !['completed','failed'].includes(state.listJobs()[0]?.status))return;armed=false;mutations++;job.workerId='changed-after-store';job.workerGeneration=99;}});jobs=new CodexJobRegistry({stateStore:state,allowedRoots:[process.cwd()]});const ack=vi.fn();jobs.attachUpstream(upstream(ack));
 try{job=jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});if(kind==='rejected')throw Error('original-reject');return kind==='normal'?result:{...result,isError:true};});const p=job.promise;armed=true;await p;jobs.pinNonforcingShutdown();record('store-authority-'+kind,{mutations,liveWorker:job.workerId,sqlWorker:state.listJobs()[0].workerId,status:job.status,ackCalls:ack.mock.calls.length,retained:(jobs as any).nonforcingLateObservationCount,resource:jobs.observeNonforcingExit()});expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test('NEW ACK callback cannot alter final original worker authority without retained UNKNOWN',async()=>{
 const {state,jobs}=fixture();let job:any;let calls=0;jobs.attachUpstream(upstream(()=>{calls++;job.workerId='changed-in-ack';job.workerGeneration=99;}));
 try{job=jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});return result;});await job.promise;jobs.pinNonforcingShutdown();record('ack-authority',{calls,liveWorker:job.workerId,sqlWorker:state.listJobs()[0].workerId,status:job.status,retained:(jobs as any).nonforcingLateObservationCount,resource:jobs.observeNonforcingExit()});expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test('NEW successful rollback undo cannot replace original worker authority before retry',async()=>{
 const {state,jobs}=fixture();const ack=vi.fn();jobs.attachUpstream(upstream(ack));const upsert=state.upsertJob.bind(state);let conflict=false,undoCalls=0;state.upsertJob=((j:any)=>{if(j.status==='completed'&&!conflict){conflict=true;throw Error('fixture first terminal conflict');}return upsert(j);}) as any;
 try{const job=jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});return result;},(_r,current)=>()=>{undoCalls++;current.workerId='changed-in-undo';current.workerGeneration=99;});await job.promise;jobs.pinNonforcingShutdown();record('undo-authority',{undoCalls,liveWorker:job.workerId,sqlWorker:state.listJobs()[0].workerId,status:job.status,ackCalls:ack.mock.calls.length,retained:(jobs as any).nonforcingLateObservationCount,resource:jobs.observeNonforcingExit()});expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test.each(['resolved','rejected'])('NEW committed-store pin retains exact original %s producer object',async kind=>{
 let jobs:any,job:any,armed=false;const raw=kind==='resolved'?{content:[{type:'text',text:'original-object'}]}:new Error('original-error-object');const state=new BridgeStateStore({file:':memory:',onTransactionCommitted:()=>{if(armed){armed=false;jobs.pinNonforcingShutdown();}}});jobs=new CodexJobRegistry({stateStore:state,allowedRoots:[process.cwd()]});
 try{job=jobs.start(input(),async()=>{if(kind==='rejected')throw raw;return raw as any;});const id=job.jobId,p=job.promise;armed=true;await p;const retained=(jobs as any).deferredSettlements.get(id);expect(retained.kind).toBe(kind);expect(kind==='resolved'?retained.result:retained.error).toBe(raw);expect(job.status).toBe('running');expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test.each(['normal','upstream-error'])('NEW %s callback readonly configurable descriptor remains safely applicable',async kind=>{
 const {state,jobs}=fixture();const ack=vi.fn();jobs.attachUpstream(upstream(ack));try{const job=jobs.start(input(),async()=>kind==='normal'?result:{...result,isError:true},(_r,current)=>{Object.defineProperty(current,'status',{value:current.status,writable:false,configurable:true,enumerable:true});});await job.promise;expect(job.status).toBe(kind==='normal'?'completed':'failed');expect(ack).toHaveBeenCalledOnce();jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().exited).toBe(true);}finally{state.close();}
});
test('NEW malformed completion argument retains exact original producer and unused returned undo',async()=>{
 const {state,jobs}=fixture();const raw={content:[{type:'text',text:'original-body'}],isError:true};let argument:any,reads=0,calls=0;const undo=()=>{calls++;};try{const job=jobs.start(input(),async()=>raw,(value:any)=>{argument=value;Object.defineProperty(value,'content',{get(){reads++;return [];}});return undo;});const id=job.jobId;await job.promise;expect(reads).toBe(0);expect(calls).toBe(0);expect((jobs as any).deferredSettlements.get(id).result).toBe(raw);const obs=(jobs as any).nonforcingLateObservations.get(id);expect(obs).toContainEqual({kind:'completion-result-data',value:argument});expect(obs).toContainEqual({kind:'completion-undo-capability',value:undo});jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');}finally{state.close();}
});
test('NEW ordinary thread metadata update still retains original producer and valid undo compatibility',async()=>{
 const {state,jobs}=fixture();const ack=vi.fn(),undo=vi.fn();jobs.attachUpstream(upstream(ack));try{const job=jobs.start(input(),async()=>result,(_r,current)=>{current.sessionDecision.threadId='original-valid-thread';current.threadId='original-valid-thread';return undo;});await job.promise;expect(job.threadId).toBe('original-valid-thread');expect(job.status).toBe('completed');expect(undo).not.toHaveBeenCalled();expect(ack).toHaveBeenCalledOnce();jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().exited).toBe(true);}finally{state.close();}
});

test('ROOT native ACK fulfillment rechecks the original worker binding',async()=>{
 const {state,jobs}=fixture();let finish!:()=>void;const pending=new Promise<void>(r=>finish=r);jobs.attachUpstream(upstream(()=>pending));
 try{const job=jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});return result;});await job.promise;job.workerId='changed-during-ack';finish();await Promise.resolve();await Promise.resolve();jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');expect([...(jobs as any).nonforcingLateObservations.get(job.jobId)]).toContainEqual(expect.objectContaining({kind:'ack-fulfillment-boundary'}));}finally{finish();state.close();}
});
test('ROOT auth boundary callback cannot mutate the worker before execution ACK',async()=>{
 let job:any,armed=false;const {state,jobs}=fixture({authBoundary:()=>{if(armed){job.workerId='changed-in-auth';armed=false;}return 'owner-boundary';}});const ack=vi.fn();jobs.attachUpstream(upstream(ack));
 try{job=jobs.start(input(),async(_p,a)=>{a({backendKind:'app-server',workerId:'original-worker',workerGeneration:1});armed=true;return result;});await job.promise;jobs.pinNonforcingShutdown();expect(jobs.observeNonforcingExit().outcome).toBe('uncertain');expect(ack).not.toHaveBeenCalled();expect(state.listJobs()[0].workerId).toBe('original-worker');}finally{state.close();}
});
