// Retained independent native regressions from rejected exact39209a8.
import {test,expect,vi} from 'vitest';import Database from 'better-sqlite3';import {randomUUID} from 'node:crypto';import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import path from 'node:path';import {StateDatabaseShutdownFence} from '../src/stateDatabaseShutdownFence.js';import {BridgeStateStore} from '../src/stateStore.js';
function fixture(){const native=new Database(':memory:');native.exec('CREATE TABLE t(x);INSERT INTO t VALUES(1),(2)');const fence=new StateDatabaseShutdownFence(native);return {native,fence,db:fence.database};}
function cleanup(native:Database.Database){if(native.open)native.close();}
test('R1 borrowed public database exec must not bypass a pinned facade',()=>{const {native,fence,db}=fixture();try{fence.pinNonforcingShutdown();expect(()=>Database.prototype.exec.call(db,'INSERT INTO t VALUES(3)')).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(native.prepare('SELECT COUNT(*) n FROM t').get()).toEqual({n:2});}finally{cleanup(native);}});
test('R1 borrowed public prepare must not create an unguarded cached statement after pin',()=>{const {native,fence,db}=fixture();try{fence.pinNonforcingShutdown();expect(()=>Database.prototype.prepare.call(db,'INSERT INTO t VALUES(3)').run()).toThrow('STATE_DATABASE_NONFORCING_PINNED');}finally{cleanup(native);}});
test('R1 borrowed public ordinary close must retain ordinary history rather than produce EXIT',()=>{const {native,fence,db}=fixture();Database.prototype.close.call(db);fence.pinNonforcingShutdown();expect(fence.closeNonforcing().outcome).toBe('uncertain');cleanup(native);});
test('R2 transaction variants must preserve database binding and chained variants',()=>{const {native,db}=fixture();try{const tx=db.transaction(function(this:{x:number}){return this.x;});expect(tx.default).toBe(tx);expect(tx.immediate.database).toBe(db);expect(tx.immediate.deferred.call({x:9})).toBe(9);}finally{cleanup(native);}});
test('retained chained statement handles and extracted operations remain pinned',()=>{const {native,fence,db}=fixture();try{const stmt=db.prepare('SELECT x FROM t').raw(true).safeIntegers(true);const operations=[stmt.get,stmt.all,stmt.iterate,stmt.columns,stmt.pluck,stmt.raw,stmt.safeIntegers,stmt.bind];fence.pinNonforcingShutdown();for(const op of operations)expect(()=>op()).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(stmt.database).toBe(db);}finally{cleanup(native);}});
test('cached transaction call/apply/bind/variants remain guarded',()=>{const {native,fence,db}=fixture();try{const tx=db.transaction(function(this:{x:number}){return this.x;});const bound=tx.bind({x:5});const immediate=tx.immediate;expect(bound()).toBe(5);expect(tx.apply({x:7},[])).toBe(7);expect(immediate.call({x:8})).toBe(8);fence.pinNonforcingShutdown();for(const f of [()=>bound(),()=>tx.call({x:3}),()=>tx.apply({x:3},[]),()=>immediate.call({x:3}),()=>tx.bind({x:3})])expect(f).toThrow('STATE_DATABASE_NONFORCING_PINNED');}finally{cleanup(native);}});
test('nested transaction callback pin rolls back all enclosing mutations',()=>{const {native,fence,db}=fixture();try{const inner=db.transaction(()=>{db.prepare('INSERT INTO t VALUES(4)').run();fence.pinNonforcingShutdown();});const outer=db.transaction(()=>{db.prepare('INSERT INTO t VALUES(3)').run();try{inner();}catch{}return 5;});expect(outer).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(native.prepare('SELECT COUNT(*) n FROM t').get()).toEqual({n:2});expect(fence.observeNonforcingExit().outcome).toBe('uncertain');}finally{cleanup(native);}});
test('reentrant SQL function pin retains active-native UNKNOWN even after unwind',()=>{const {native,fence,db}=fixture();try{db.function('pin',()=>{fence.pinNonforcingShutdown();return 4;});expect(db.prepare('SELECT pin() x').get()).toEqual({x:4});expect(fence.closeNonforcing().outcome).toBe('uncertain');expect(fence.observeNonforcingExit().outcome).toBe('uncertain');expect(native.open).toBe(true);}finally{cleanup(native);}});
test('existing raw BEGIN transaction at pin is UNKNOWN after explicit ROLLBACK',()=>{const {native,fence,db}=fixture();try{db.exec('BEGIN;INSERT INTO t VALUES(3)');fence.pinNonforcingShutdown();db.exec('ROLLBACK');expect(native.inTransaction).toBe(false);expect(fence.closeNonforcing().outcome).toBe('uncertain');expect(native.prepare('SELECT COUNT(*) n FROM t').get()).toEqual({n:2});}finally{cleanup(native);}});
test('multiple retained iterators block closure until every cleanup return',()=>{const {native,fence,db}=fixture();try{const one=db.prepare('SELECT x FROM t').iterate(),two=db.prepare('SELECT x FROM t').iterate();one.next();two.next();fence.pinNonforcingShutdown();expect(fence.closeNonforcing().outcome).toBe('timeout');one.return!();expect(fence.closeNonforcing().outcome).toBe('timeout');two.return!();expect(fence.closeNonforcing().exited).toBe(true);}finally{cleanup(native);}});
test('completed iterator no longer blocks actual closure and retained next stays fenced',()=>{const {native,fence,db}=fixture();try{const it=db.prepare('SELECT x FROM t').iterate();expect([...it]).toEqual([{x:1},{x:2}]);fence.pinNonforcingShutdown();expect(fence.closeNonforcing().exited).toBe(true);expect(()=>it.next()).toThrow('STATE_DATABASE_NONFORCING_PINNED');}finally{cleanup(native);}});
test('captured native close cannot be substituted after construction and occurs at most once',()=>{const {native}=fixture();const close=native.close.bind(native),spy=vi.fn(()=>close());native.close=spy as any;const fence=new StateDatabaseShutdownFence(native);native.close=vi.fn(()=>{throw Error('replacement');}) as any;fence.pinNonforcingShutdown();expect(fence.closeNonforcing().exited).toBe(true);expect(fence.closeNonforcing().exited).toBe(true);expect(fence.observeNonforcingExit().exited).toBe(true);expect(spy).toHaveBeenCalledOnce();});
test('native close success-with-open must stick UNKNOWN and never retry',()=>{const {native}=fixture();const close=native.close.bind(native),spy=vi.fn(()=>{});native.close=spy as any;const fence=new StateDatabaseShutdownFence(native);try{fence.pinNonforcingShutdown();expect(fence.closeNonforcing().outcome).toBe('uncertain');expect(fence.closeNonforcing().outcome).toBe('uncertain');expect(spy).toHaveBeenCalledOnce();expect(native.open).toBe(true);}finally{close();}});
test('actual resource close then exception remains UNKNOWN despite closed native state',()=>{const {native}=fixture();const close=native.close.bind(native),spy=vi.fn(()=>{close();throw Error('after-close');});native.close=spy as any;const fence=new StateDatabaseShutdownFence(native);fence.pinNonforcingShutdown();expect(fence.closeNonforcing().outcome).toBe('uncertain');expect(native.open).toBe(false);expect(fence.observeNonforcingExit().outcome).toBe('uncertain');expect(fence.closeNonforcing().outcome).toBe('uncertain');expect(spy).toHaveBeenCalledOnce();});
test('pending native asynchronous backup pin never becomes EXIT after backup completes',async()=>{const {native,fence,db}=fixture();const root=mkdtempSync(path.join(process.env.TMPDIR!,'review-backup-'));try{const pending=db.backup(path.join(root,'copy.sqlite'));fence.pinNonforcingShutdown();expect(fence.closeNonforcing().outcome).toBe('uncertain');await pending;expect(fence.observeNonforcingExit().outcome).toBe('uncertain');expect(native.open).toBe(true);}finally{cleanup(native);rmSync(root,{recursive:true});}});
test('BridgeStateStore resource closure leaves durable bridge_instances evidence unchanged',()=>{const store=new BridgeStateStore({file:':memory:'});const native=(store as any).databaseShutdown.owned as Database.Database;try{const row=native.prepare('SELECT * FROM bridge_instances WHERE instance_id=?').get(store.bridgeInstanceId);store.pinNonforcingShutdown();expect(()=>store.close()).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(native.prepare('SELECT * FROM bridge_instances WHERE instance_id=?').get(store.bridgeInstanceId)).toEqual(row);expect(store.closeNonforcing().exited).toBe(true);expect(store.observeNonforcingExit().exited).toBe(true);}finally{cleanup(native);}});
test('R1 borrowed native call can mutate retirement evidence while facade pin reports EXIT',()=>{const store=new BridgeStateStore({file:':memory:'});const db=(store as any).database as Database.Database,native=(store as any).databaseShutdown.owned as Database.Database;try{store.pinNonforcingShutdown();expect(()=>Database.prototype.prepare.call(db,"UPDATE bridge_instances SET stopped_at=1,termination_reason='fabricated' WHERE instance_id=?").run(store.bridgeInstanceId)).toThrow('STATE_DATABASE_NONFORCING_PINNED');}finally{cleanup(native);}});
test('pin at native COMMIT trace is retained UNKNOWN (already executing native commit)',()=>{let fence:StateDatabaseShutdownFence|undefined;const native=new Database(':memory:',{verbose:sql=>{if(sql==='COMMIT')fence?.pinNonforcingShutdown();}});native.exec('CREATE TABLE t(x)');fence=new StateDatabaseShutdownFence(native);try{const tx=fence.database.transaction(()=>fence!.database.prepare('INSERT INTO t VALUES(9)').run());tx();expect(fence.closeNonforcing().outcome).toBe('uncertain');expect(native.prepare('SELECT * FROM t').all()).toEqual([{x:9}]);}finally{cleanup(native);}});
test('BridgeStateStore own transaction pin prevents COMMIT and rolls back prior write',()=>{const store=new BridgeStateStore({file:':memory:'}),native=(store as any).databaseShutdown.owned as Database.Database;try{expect(()=>store.transaction(()=>{store.setMeta('review_before_pin','value');store.pinNonforcingShutdown();})).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(native.prepare("SELECT value FROM bridge_meta WHERE key='review_before_pin'").get()).toBeUndefined();expect(store.closeNonforcing().outcome).toBe('uncertain');}finally{cleanup(native);}});
test('a reopened read-only state connection receives its own fresh resource fence',()=>{const root=mkdtempSync(path.join(process.env.TMPDIR!,'review-state-readonly-')),file=path.join(root,'state.sqlite');let reader:BridgeStateStore|undefined;try{const writer=new BridgeStateStore({file});writer.setMeta('review_readonly','value');writer.close();reader=new BridgeStateStore({file,readOnly:true});const read=reader.getMeta.bind(reader);expect(read('review_readonly')).toBe('value');reader.pinNonforcingShutdown();expect(()=>read('review_readonly')).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(reader.closeNonforcing().exited).toBe(true);}finally{if(reader)cleanup((reader as any).databaseShutdown.owned);rmSync(root,{recursive:true});}});

test('borrowed native transaction reentry rolls back through guarded compatibility handles',()=>{
 const {native,fence,db}=fixture();try {
  const transaction=Database.prototype.transaction.call(db,()=>{db.prepare('INSERT INTO t VALUES(3)').run();fence.pinNonforcingShutdown();});
  expect(transaction).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(native.inTransaction).toBe(false);expect(native.prepare('SELECT COUNT(*) n FROM t').get()).toEqual({n:2});expect(fence.closeNonforcing().outcome).toBe('uncertain');
 }finally{cleanup(native);}
});
test('borrowed native prepare before pin returns a guarded cached statement',()=>{
 const {native,fence,db}=fixture();try {
  const statement=Database.prototype.prepare.call(db,'INSERT INTO t VALUES(3)');const run=statement.run;expect(statement.database).toBe(db);fence.pinNonforcingShutdown();expect(run).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(native.prepare('SELECT COUNT(*) n FROM t').get()).toEqual({n:2});expect(fence.closeNonforcing().exited).toBe(true);
 }finally{cleanup(native);}
});
test('borrowed nested transaction cannot retain uncommitted writes after pin',()=>{
 const {native,fence,db}=fixture();try {
  const inner=Database.prototype.transaction.call(db,()=>{db.prepare('INSERT INTO t VALUES(4)').run();fence.pinNonforcingShutdown();});
  const outer=Database.prototype.transaction.call(db,()=>{db.prepare('INSERT INTO t VALUES(3)').run();inner();});
  expect(outer).toThrow('STATE_DATABASE_NONFORCING_PINNED');expect(native.inTransaction).toBe(false);expect(native.prepare('SELECT COUNT(*) n FROM t').get()).toEqual({n:2});expect(fence.closeNonforcing().outcome).toBe('uncertain');
 }finally{cleanup(native);}
});
