import {test,expect} from 'vitest';import {validateHeaderValue} from 'node:http';import {readFileSync} from 'node:fs';import {isLoopbackOAuthMetadataUrl,mcpOAuthRequested,mcpOAuthEnvironment,codexProcessEnvironment} from '../scripts/runtime-env.mjs';import {loadConfig} from '../src/config.js';import {oauthChallenge} from '../src/mcpOAuth.js';
const path='/.well-known/oauth-protected-resource/mcp',metadata='http://127.0.0.1:8765'+path;
const env:any={CODEX_MCP_BRIDGE_OAUTH_ISSUER:'https://issuer.example/tenant/',CODEX_MCP_BRIDGE_OAUTH_RESOURCE:'https://resource.example/mcp',CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata,CODEX_MCP_BRIDGE_OAUTH_JWKS_URI:'https://issuer.example/keys',CODEX_MCP_BRIDGE_OAUTH_OPERATOR_SUBJECT:'fixture-operator',CODEX_MCP_BRIDGE_TOKEN:'private-fixture-sealing-secret-1234567890'};
function flag(e:any,host='127.0.0.1',port='8765'){return mcpOAuthRequested(e)&&isLoopbackOAuthMetadataUrl(e.CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL??e.CODEX_GPT_BRIDGE_OAUTH_RESOURCE_METADATA_URL??'',host,port);}
for(const [host,authority] of [['127.0.0.1','127.0.0.1'],['localhost','localhost'],['::1','[::1]']])for(const suffix of ['','/mcp'])test('fresh exact metadata control '+host+suffix,()=>{const url='http://'+authority+':8765/.well-known/oauth-protected-resource'+suffix;expect(isLoopbackOAuthMetadataUrl(url,host,8765)).toBe(true);expect(loadConfig({...env,CODEX_MCP_BRIDGE_HOST:host,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:url}).oauth?.resourceMetadataUrl).toBe(url);});
for(const url of ['http://127.0.0.1:8766'+path,'http://localhost:8765'+path,'http://127.0.0.2:8765'+path,'http://192.168.0.1:8765'+path,'http://public.example:8765'+path,'http://user:secret@127.0.0.1:8765'+path,'http://127.0.0.1:8765'+path+'?next=/mcp','http://127.0.0.1:8765'+path+'#fragment','http://127.0.0.1:8765/mcp','http://127.0.0.1:8765/api/settings','http://127.0.0.1:8765/.well-known/oauth-protected-resource/%6dcp','http://127.0.0.1:8765'+path+'\n'])test('fresh ordinary hostile URL refused '+JSON.stringify(url),()=>{expect(isLoopbackOAuthMetadataUrl(url,'127.0.0.1',8765)).toBe(false);expect(()=>loadConfig({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:url})).toThrow('HTTPS');expect(flag({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:url})).toBe(false);});
for(const field of ['ISSUER','RESOURCE','JWKS_URI'])test('fresh plaintext exception does not reach '+field,()=>{expect(()=>loadConfig({...env,['CODEX_MCP_BRIDGE_OAUTH_'+field]:metadata})).toThrow('HTTPS');});
test('fresh valid public HTTPS metadata remains ordinary no-plaintext control',()=>{const e={...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:'https://metadata.example/.well-known/oauth-protected-resource/mcp'};expect(loadConfig(e).oauth?.resourceMetadataUrl).toBe(e.CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL);expect(flag(e)).toBe(false);});
test('fresh local valid metadata produces valid quoted HTTP challenge',()=>{const config=loadConfig(env);expect(()=>validateHeaderValue('WWW-Authenticate',oauthChallenge(config.oauth!))).not.toThrow();expect(flag(env)).toBe(true);expect(config.noAuth).toBe(false);});
test('fresh OAuth and NoAuth cannot mix',()=>{expect(()=>loadConfig({...env,CODEX_MCP_BRIDGE_NO_AUTH:'1'})).toThrow('cannot be combined');});
test('fresh partial OAuth fields fail closed',()=>{expect(()=>loadConfig({CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata})).toThrow('requires');});
test('fresh current invalid metadata wins over valid legacy without fallback',()=>{expect(()=>loadConfig({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata+'?q=1',CODEX_GPT_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata})).toThrow('HTTPS');expect(flag({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata+'?q=1',CODEX_GPT_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata})).toBe(false);});
test('fresh empty current metadata cannot inherit valid legacy',()=>{expect(()=>loadConfig({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:'',CODEX_GPT_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata})).toThrow('requires');expect(flag({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:'',CODEX_GPT_BRIDGE_OAUTH_RESOURCE_METADATA_URL:metadata})).toBe(false);});
test('fresh legacy OAuth profile has matching exact exception',()=>{const legacy=Object.fromEntries(Object.entries(env).map(([k,v])=>[k.replace('CODEX_MCP_BRIDGE_','CODEX_GPT_BRIDGE_'),v]));expect(loadConfig(legacy).oauth?.resourceMetadataUrl).toBe(metadata);expect(flag(legacy)).toBe(true);});
test('fresh no OAuth cannot enable plaintext option',()=>{expect(flag({})).toBe(false);});
test('fresh OAuth environment project keeps sealing profile while Codex projection excludes it',()=>{const selected=mcpOAuthEnvironment({...env,CONTROL_PLANE_API_KEY:'fixture-control-key',OTHER:'unrelated'});expect(selected.CODEX_MCP_BRIDGE_TOKEN).toBe(env.CODEX_MCP_BRIDGE_TOKEN);expect(selected).not.toHaveProperty('CONTROL_PLANE_API_KEY');const child=codexProcessEnvironment({...env,CONTROL_PLANE_API_KEY:'fixture-control-key'});expect(child).not.toHaveProperty('CONTROL_PLANE_API_KEY');expect(child).not.toHaveProperty('CODEX_MCP_BRIDGE_OAUTH_ISSUER');});
for(const [label,url] of [['emptyquery',metadata+'?'],['emptyfragment',metadata+'#'],['emptyuserinfo','http://@127.0.0.1:8765'+path],['shortIPv4','http://127.1:8765'+path],['integerIPv4','http://2130706433:8765'+path],['dotsegment','http://127.0.0.1:8765/private/..'+path]])test('fresh strict raw metadata boundary refuses '+label,()=>{expect(isLoopbackOAuthMetadataUrl(url,'127.0.0.1',8765)).toBe(false);expect(()=>loadConfig({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:url})).toThrow();expect(flag({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:url})).toBe(false);});
for(const code of [1,7,31])test('fresh raw C0 metadata control rejected before it can break a header '+code,()=>{const url=metadata+String.fromCharCode(code);let config:any;try{config=loadConfig({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:url});}catch{return;}const challenge=oauthChallenge(config.oauth);console.log('raw-control-accepted',{code,helper:isLoopbackOAuthMetadataUrl(url,'127.0.0.1',8765),flag:flag({...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:url})});expect(()=>validateHeaderValue('WWW-Authenticate',challenge)).not.toThrow();expect(config.oauth.resourceMetadataUrl).not.toBe(url);});
test('fresh launcher exact source contains pre-child OAuth config validation and isolated optional flag',()=>{const source=readFileSync(new URL('../scripts/start-codex-mcp-bridge.mjs',import.meta.url),'utf8');expect(source).toContain('loadConfig({ ...process.env, CODEX_MCP_BRIDGE_HOST: host, CODEX_MCP_BRIDGE_PORT: port });');expect(source.indexOf('loadConfig({ ...process.env')).toBeLessThan(source.indexOf('runtimeLocks = acquireRuntimeOwnershipLocks'));expect(source).toContain('? ["--harpoon.allow-plaintext-http=true"] : []');expect(source).toContain('MCP OAuth requires HTTP transport');});
test('fresh exact launcher option expression stays absent for noOAuth HTTPS or different binding',()=>{const source=readFileSync(new URL('../scripts/start-codex-mcp-bridge.mjs',import.meta.url),'utf8'),start=source.indexOf('...(mcpOAuthRequested(process.env) && isLoopbackOAuthMetadataUrl(');expect(start).toBeGreaterThan(0);const end=source.indexOf(' : [])',start),expression=source.slice(start+4,end+5);const actual=new Function('mcpOAuthRequested','isLoopbackOAuthMetadataUrl','process','host','port','return ('+expression+');');expect(actual(mcpOAuthRequested,isLoopbackOAuthMetadataUrl,{env:{}},'127.0.0.1','8765')).toEqual([]);expect(actual(mcpOAuthRequested,isLoopbackOAuthMetadataUrl,{env:{...env,CODEX_MCP_BRIDGE_OAUTH_RESOURCE_METADATA_URL:'https://metadata.example'+path}},'127.0.0.1','8765')).toEqual([]);expect(actual(mcpOAuthRequested,isLoopbackOAuthMetadataUrl,{env},'127.0.0.1','8766')).toEqual([]);expect(actual(mcpOAuthRequested,isLoopbackOAuthMetadataUrl,{env},'127.0.0.1','8765')).toEqual(['--harpoon.allow-plaintext-http=true']);});

for(const host of ['127.0.0.1','localhost','::1'])test('explicit and implicit default HTTP port remain valid '+host,()=>{const authority=host==='::1'?'[::1]':host;for(const port of ['',':80'])expect(isLoopbackOAuthMetadataUrl('http://'+authority+port+path,host,80)).toBe(true);});
for(const field of ['ISSUER','RESOURCE','JWKS_URI','RESOURCE_METADATA_URL'])for(const suffix of ['?', '#',String.fromCharCode(1),String.fromCharCode(31),String.fromCharCode(127)])test('HTTPS original raw URL rejects empty markers/control '+field+JSON.stringify(suffix),()=>{expect(()=>loadConfig({...env,['CODEX_MCP_BRIDGE_OAUTH_'+field]:'https://issuer.example/mcp'+suffix})).toThrow('HTTPS');});
for(const field of ['ISSUER','RESOURCE','JWKS_URI','RESOURCE_METADATA_URL'])test('HTTPS original URL rejects empty credential marker '+field,()=>{expect(()=>loadConfig({...env,['CODEX_MCP_BRIDGE_OAUTH_'+field]:'https://@issuer.example/mcp'})).toThrow('HTTPS');});
