/**
 * Generated by `npm run release:sync` from the final self-contained card HTML.
 * Do not edit this file by hand.
 */
export const UI_RESOURCE_MANIFEST = {
  "manifestVersion": 3,
  "strategy": "versioned-uri",
  "hashAlgorithm": "sha256",
  "minimumContractGeneration": {
    "settings": 9,
    "dashboard": 6
  },
  "releaseInventory": {
    "catalog": "ui-release-catalog.json",
    "catalogSha256": "ca50c51cd1534f67a20f7dd2f6e00bab11caa7baee8a86da6fcfe8e8d08e895a",
    "activeResources": [
      "settings",
      "dashboard"
    ],
    "compatibilityResources": [],
    "retirement": {
      "activity": {
        "lifecycle": "historical-revisions-retired",
        "newPresentations": false,
        "replacement": "dashboard",
        "firstStableWithReplacement": "0.4.1",
        "minimumSupportRule": "none",
        "statePreserved": [
          "activities",
          "agents",
          "jobs",
          "results",
          "idempotency"
        ]
      },
      "question": {
        "lifecycle": "historical-revisions-retired",
        "newPresentations": false,
        "replacement": "host-conversation",
        "firstStableWithReplacement": "0.4.1",
        "minimumSupportRule": "none",
        "statePreserved": [
          "questions",
          "idempotency"
        ]
      }
    },
    "selected": [
      {
        "name": "settings",
        "uriVersion": 3,
        "digest": "b46c5b0e1346a619e65abc1b2270aaf3edf1d9afd6be9965d5529a37028e5d67",
        "uri": "ui://codex-mcp-bridge/settings/v3.html",
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_settings",
        "requiredTools": [
          "codex_settings",
          "codex_ui_read",
          "codex_update_settings"
        ]
      },
      {
        "name": "dashboard",
        "uriVersion": 2,
        "digest": "62f2d44ad632632d459f55da11bf1a7ac3fdd6d4401646fbe82e59db6d90699d",
        "uri": "ui://codex-mcp-bridge/dashboard/v2.html",
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_dashboard",
        "requiredTools": [
          "codex_dashboard",
          "codex_status",
          "codex_ui_completion",
          "codex_ui_problem",
          "codex_ui_read",
          "codex_interaction_respond"
        ]
      }
    ]
  },
  "resources": {
    "settings": {
      "uriVersion": 3,
      "digest": "b46c5b0e1346a619e65abc1b2270aaf3edf1d9afd6be9965d5529a37028e5d67",
      "uri": "ui://codex-mcp-bridge/settings/v3.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Settings",
          "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": false,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, experimental direct-result delivery, Codex-app thread visibility, interface language, history, and concurrency for Codex MCP Bridge for ChatGPT.",
          "openai/widgetPrefersBorder": false,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 24
        }
      },
      "releaseProvenance": {
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_settings",
        "requiredTools": [
          "codex_settings",
          "codex_ui_read",
          "codex_update_settings"
        ]
      }
    },
    "dashboard": {
      "uriVersion": 2,
      "digest": "62f2d44ad632632d459f55da11bf1a7ac3fdd6d4401646fbe82e59db6d90699d",
      "uri": "ui://codex-mcp-bridge/dashboard/v2.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Codex Status",
          "description": "Codex status card with conversation-first defaults, an all-conversations view, nested Agents, retained turn history, and validated request review.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": false,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Shows Codex work and history from this conversation when records exist, otherwise all conversations. Switch scope at the top; both views use the same execution states and approval/input request review.",
          "openai/widgetPrefersBorder": false,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": [],
            "redirect_domains": [
              "https://chatgpt.com"
            ]
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 37
        }
      },
      "releaseProvenance": {
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_dashboard",
        "requiredTools": [
          "codex_dashboard",
          "codex_status",
          "codex_ui_completion",
          "codex_ui_problem",
          "codex_ui_read",
          "codex_interaction_respond"
        ]
      }
    }
  }
} as const;

export type UiResourceName = keyof typeof UI_RESOURCE_MANIFEST.resources;
